"""Build a deduplicated master glossary from every in-game `glossary` block in the season data.

In-game glossaries live as `{id: {name, description}}` dicts attached to skills, gear, pact spirits,
hero traits, slates, and talent trees. This collects them all, dedups by glossary id (each id maps to
one consistent name; the longest description wins on the rare variant), and writes:
  - docs/MASTER_GLOSSARY.md   — alphabetical, grep/read-friendly (the searchable reference)
  - data/master_glossary.json — { name: {id, description, sources, source_files} }

Regenerate after a data import:  py -3.12 tools/build_master_glossary.py [season]
"""
from __future__ import annotations
import json
import os
import sys
from collections import defaultdict

_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
_DATA = os.path.join(_ROOT, "data")

# Map a season filename to a human source category.
def _category(fname: str) -> str:
    table = {
        "_skills.json": "skills", "_legendary_gear.json": "gear",
        "_pact_spirits.json": "spirits", "_hero_traits.json": "hero traits",
        "_divinity_slates.json": "slates", "_hero_memories.json": "memories",
        "_craft_base_types.json": "crafting", "_grafts.json": "grafts",
    }
    if fname in table:
        return table[fname]
    if not fname.startswith("_"):
        return "talents"  # per-tree files: warrior.json, marksman.json, …
    return fname[1:-5]


def _walk(node, fname, sink):
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "glossary" and isinstance(v, dict):
                for gid, entry in v.items():
                    if isinstance(entry, dict) and entry.get("name"):
                        sink(str(gid), entry["name"].strip(),
                             (entry.get("description") or "").strip(), fname)
            else:
                _walk(v, fname, sink)
    elif isinstance(node, list):
        for v in node:
            _walk(v, fname, sink)


def collect(season: str) -> dict:
    sdir = os.path.join(_DATA, "seasons", season)
    by_id: dict[str, dict] = defaultdict(lambda: {"name": "", "descs": defaultdict(int), "files": set()})

    def sink(gid, name, desc, fname):
        rec = by_id[gid]
        rec["name"] = name  # consistent per id (verified)
        if desc:
            rec["descs"][desc] += 1
        rec["files"].add(fname)

    for fn in sorted(os.listdir(sdir)):
        if not fn.endswith(".json"):
            continue
        try:
            data = json.load(open(os.path.join(sdir, fn), encoding="utf-8"))
        except Exception:
            continue
        _walk(data, fn, sink)

    # Resolve: longest description wins; categorize sources.
    terms = []
    for gid, rec in by_id.items():
        desc = max(rec["descs"], key=lambda d: (rec["descs"][d], len(d))) if rec["descs"] else ""
        cats = sorted({_category(f) for f in rec["files"]})
        terms.append({"id": gid, "name": rec["name"], "description": desc,
                      "sources": cats, "source_files": sorted(rec["files"])})
    terms.sort(key=lambda t: (t["name"].lower(), t["id"]))
    return {"season": season, "term_count": len(terms), "terms": terms}


def write_outputs(g: dict) -> tuple[str, str]:
    season = g["season"]
    json_path = os.path.join(_DATA, "master_glossary.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(g, f, ensure_ascii=False, indent=2)

    md_path = os.path.join(_ROOT, "docs", "MASTER_GLOSSARY.md")
    lines = [
        f"# Master Glossary (season {season})",
        "",
        f"Deduplicated from every in-game `glossary` block across the season data "
        f"({g['term_count']} terms). Generated by `backend/tools/build_master_glossary.py` — "
        "regenerate after a data import; do not hand-edit. Grep a term name (`### `) to jump to it.",
        "",
        "---",
        "",
    ]
    for t in g["terms"]:
        lines.append(f"### {t['name']}")
        lines.append("")
        lines.append(t["description"] or "_(no description in data)_")
        lines.append("")
        lines.append(f"<sub>id {t['id']} · sources: {', '.join(t['sources'])}</sub>")
        lines.append("")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return json_path, md_path


def main() -> None:
    season = sys.argv[1] if len(sys.argv) > 1 else None
    if season is None:
        try:
            sys.path.insert(0, os.path.join(_ROOT, "backend"))
            from persistence import season_manager
            season = season_manager.get_active_season() or "SS12"
        except Exception:
            season = "SS12"
    g = collect(season)
    jp, mp = write_outputs(g)
    print(f"Master glossary: {g['term_count']} terms (season {season})")
    print(f"  {os.path.relpath(jp, _ROOT)}")
    print(f"  {os.path.relpath(mp, _ROOT)}")


if __name__ == "__main__":
    main()
