"""Export the season-global reference catalogs as static JSON for the web (CDN) build.

Runs the SAME endpoint logic the desktop app already consumes (server.py's catalog handlers), so the static
files are byte-for-byte what the app expects — the web build fetches these from a CDN instead of hitting the
Python backend, removing ~16 MB + the catalog endpoints from the server (Phase 1 of the web-hosting plan).

Output layout (cache-busted by season):
    <out>/manifest.json                  -> {"season": "SS12"}
    <out>/<season>/<catalog>.json        -> e.g. SS12/skills.json

Usage:  python backend/tools/export_web_data.py [--out DIR]   (default: <repo>/web-data)
"""
import argparse
import json
import os
import shutil
import sys

_BACKEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

import server  # noqa: E402  (path set above)

# endpoint handler -> output filename (matches the names the web client will request)
CATALOGS = {
    "conditions": server.get_conditions,
    "skills": server.get_skills,
    "hero_traits": server.get_hero_traits,
    "legendary_gear_index": server.get_legendary_gear_index,
    "legendary_gear": server.get_legendary_gear,
    "pact_spirits": server.get_pact_spirits,
    "craft_base_types": server.get_craft_base_types,
    "craft_base_items": server.get_craft_base_items,
    "grafts": server.get_grafts,
    "hero_memories": server.get_hero_memories,
    "verification_db": server.get_verification_db,
    "glossary": server.get_glossary,
    "help_db": server.get_help_db,
}


# CORS allowlist Function, written verbatim into <out>/functions/_middleware.js on every export.
# APP_PAGES_PROJECT is the APP's Pages project name so its preview deploys can load data.
_CORS_MIDDLEWARE_JS = """// Cloudflare Pages Function — CORS allowlist for the TLI Builder data CDN.
//
// Why a Function instead of a static `_headers` line: a static header can only emit ONE
// `Access-Control-Allow-Origin` value, so locking to the apex would break the app's
// preview deploys, www, and local dev. This reflects the request Origin back only when
// it is on the allowlist below, and refuses everyone else — so third-party sites still
// can't fetch the dataset from a visitor's browser, but our own surfaces keep working.
//
// This is browser-side friction only. It does NOT stop server-side scraping (a backend
// with no Origin header gets the file) — the data terms in DATA-LICENSE.md cover that.
//
// GENERATED by backend/tools/export_web_data.py — edit the constant there, not this file.

const ALLOWED_ORIGINS = new Set([
  'https://tlibuilder.com',
  'https://www.tlibuilder.com',
]);

// The APP's Cloudflare Pages project name (NOT `tlibuilder-data`, the data project) so
// `<hash>.<project>.pages.dev` preview deploys can load data during QA. '' disables previews.
const APP_PAGES_PROJECT = 'tlibuilder';

function isAllowedOrigin(origin) {
  if (!origin) return false;
  if (ALLOWED_ORIGINS.has(origin)) return true;
  // Local web-build dev (npm run dev / vite preview) pointed at the live CDN.
  if (/^http:\\/\\/localhost(:\\d+)?$/.test(origin)) return true;
  if (/^http:\\/\\/127\\.0\\.0\\.1(:\\d+)?$/.test(origin)) return true;
  // The app project's Pages previews, e.g. https://a1b2c3.tlibuilder.pages.dev
  if (
    APP_PAGES_PROJECT &&
    new RegExp(`^https://([a-z0-9-]+\\\\.)?${APP_PAGES_PROJECT}\\\\.pages\\\\.dev$`).test(origin)
  ) {
    return true;
  }
  return false;
}

export async function onRequest(context) {
  const { request, next } = context;
  const origin = request.headers.get('Origin');
  const allow = isAllowedOrigin(origin);

  // Preflight (only fires if a request ever adds a custom header; simple GETs skip it).
  if (request.method === 'OPTIONS') {
    const headers = new Headers({ Vary: 'Origin' });
    if (allow) {
      headers.set('Access-Control-Allow-Origin', origin);
      headers.set('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
      headers.set('Access-Control-Max-Age', '86400');
    }
    return new Response(null, { status: 204, headers });
  }

  const response = await next();
  // Reflect Origin per-request so caches never serve one origin's grant to another.
  // (Pages Function responses aren't edge-cached by default; Vary:Origin covers browsers.)
  response.headers.append('Vary', 'Origin');
  if (allow) {
    response.headers.set('Access-Control-Allow-Origin', origin);
  }
  return response;
}
"""


def _jsonable(v):
    return v.model_dump() if hasattr(v, "model_dump") else v


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(_BACKEND), "web-data"))
    args = ap.parse_args()

    season = server.season_manager.get_active_season()
    if not season:
        raise SystemExit("No active season — set one before exporting.")
    season_dir = os.path.join(args.out, season)
    os.makedirs(season_dir, exist_ok=True)

    total = 0
    print(f"Exporting season {season} -> {season_dir}")
    for name, fn in CATALOGS.items():
        data = _jsonable(fn())
        path = os.path.join(season_dir, f"{name}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        size = os.path.getsize(path)
        total += size
        print(f"  {name:22s} {size / 1024:9.1f} KB")

    # Entity icons (served via ICON_BASE on web). Copy the bundled icons dir to <out>/icons so the CDN serves
    # /icons/<category>/<file>.webp, matching iconUrl(). ~10 MB of webp; cached per-icon on demand.
    icons_src = os.path.join(server._DATA_ROOT, "images", "icons")
    if os.path.isdir(icons_src):
        icons_dst = os.path.join(args.out, "icons")
        shutil.rmtree(icons_dst, ignore_errors=True)
        shutil.copytree(icons_src, icons_dst)
        n_icons = sum(len(fs) for _, _, fs in os.walk(icons_dst))
        print(f"  icons                  {n_icons} files copied")

    with open(os.path.join(args.out, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump({"season": season}, f)

    # Cloudflare Pages _headers: caching only. CORS is NOT set here — a static header can emit
    # just one allowed origin, which would break the app's preview deploys, www, and local dev.
    # An allowlisting Pages Function (functions/_middleware.js, written below) owns CORS instead:
    # it reflects the Origin only for our own surfaces, so third-party sites can't fetch the
    # dataset from a visitor's browser. (Browser-side friction only; the data terms in
    # DATA-LICENSE.md cover server-side scraping, which no CORS rule can stop.)
    # Cache for an hour (season-in-path means a new season is a new URL; re-exports propagate within the hour).
    with open(os.path.join(args.out, "_headers"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/*\n  Cache-Control: public, max-age=3600\n")

    # The CORS allowlist Function. Emitted here so a fresh web-data/ export always ships it.
    fns_dir = os.path.join(args.out, "functions")
    os.makedirs(fns_dir, exist_ok=True)
    with open(os.path.join(fns_dir, "_middleware.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write(_CORS_MIDDLEWARE_JS)

    # Ship the data terms at the CDN root, so anyone who takes the served files also takes the
    # notice (the terms travel with the data instead of living only in the repo).
    data_license = os.path.join(os.path.dirname(_BACKEND), "DATA-LICENSE.md")
    if os.path.isfile(data_license):
        shutil.copy2(data_license, os.path.join(args.out, "DATA-LICENSE.md"))
    else:
        print("  WARNING: DATA-LICENSE.md not found at repo root — CDN export will omit it")

    print(f"  {'TOTAL':22s} {total / 1024:9.1f} KB  (~{total / 1048576:.1f} MB raw; CDN gzip/brotli -> ~1 MB on the wire)")
    print(f"  manifest.json -> {{'season': '{season}'}}")


if __name__ == "__main__":
    main()
