"""Export the season-global reference catalogs as static JSON for the web (CDN) build.

Runs the SAME endpoint logic the desktop app already consumes (server.py's catalog handlers), so the static
files are byte-for-byte what the app expects — the web build fetches these from a CDN instead of hitting the
Python backend, removing ~16 MB + the catalog endpoints from the server (Phase 1 of the web-hosting plan).

Output layout (cache-busted by season):
    <out>/manifest.json                  -> {"season": "SS12"}
    <out>/<season>/<catalog>.json        -> e.g. SS12/skills.json

Usage:  python backend/tools/export_web_data.py [--out DIR]   (default: <repo>/web-data)
"""
import argparse
import json
import os
import shutil
import sys

_BACKEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

import server  # noqa: E402  (path set above)

# endpoint handler -> output filename (matches the names the web client will request)
CATALOGS = {
    "conditions": server.get_conditions,
    "skills": server.get_skills,
    "hero_traits": server.get_hero_traits,
    "legendary_gear_index": server.get_legendary_gear_index,
    "legendary_gear": server.get_legendary_gear,
    "pact_spirits": server.get_pact_spirits,
    "craft_base_types": server.get_craft_base_types,
    "craft_base_items": server.get_craft_base_items,
    "grafts": server.get_grafts,
    "hero_memories": server.get_hero_memories,
    "verification_db": server.get_verification_db,
    "glossary": server.get_glossary,
    "help_db": server.get_help_db,
}


# CORS allowlist Worker, written verbatim into <out>/_worker.js on every export.
# Pages ADVANCED mode (a _worker.js) is required: a functions/_middleware.js is NOT compiled
# by `wrangler pages deploy <dir>`, and a Pages platform default adds
# `Access-Control-Allow-Origin: *` that a static `_headers` can't remove. The Worker serves the
# asset via env.ASSETS.fetch(), DELETES that wildcard, and sets ours only for allowlisted
# origins. APP_PAGES_PROJECT is the APP's Pages project name so its preview deploys can load data.
_CORS_WORKER_JS = """// Cloudflare Pages advanced-mode Worker — CORS allowlist for the TLI Builder data CDN.
//
// Advanced mode (this _worker.js) handles EVERY request: it serves the static asset via
// env.ASSETS.fetch(), then rewrites CORS so only our own origins get an
// Access-Control-Allow-Origin. It DELETES any pre-existing ACAO (e.g. a platform default
// wildcard) before conditionally setting ours, so a disallowed origin gets none.
//
// This is browser-side friction only. It does NOT stop server-side scraping (a backend
// with no Origin header gets the file) — the data terms in DATA-LICENSE.md cover that.
//
// GENERATED by backend/tools/export_web_data.py — edit the constant there, not this file.

const ALLOWED_ORIGINS = new Set([
  'https://tlibuilder.com',
  'https://www.tlibuilder.com',
]);

// The APP's Cloudflare Pages project name (NOT `tlibuilder-data`, the data project) so
// `<hash>.<project>.pages.dev` preview deploys can load data during QA. '' disables previews.
const APP_PAGES_PROJECT = 'tlibuilder';

function isAllowedOrigin(origin) {
  if (!origin) return false;
  if (ALLOWED_ORIGINS.has(origin)) return true;
  // Local web-build dev (npm run dev / vite preview) pointed at the live CDN.
  if (/^http:\\/\\/localhost(:\\d+)?$/.test(origin)) return true;
  if (/^http:\\/\\/127\\.0\\.0\\.1(:\\d+)?$/.test(origin)) return true;
  // The app project's Pages previews, e.g. https://a1b2c3.tlibuilder.pages.dev
  if (
    APP_PAGES_PROJECT &&
    new RegExp(`^https://([a-z0-9-]+\\\\.)?${APP_PAGES_PROJECT}\\\\.pages\\\\.dev$`).test(origin)
  ) {
    return true;
  }
  return false;
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get('Origin');
    const allow = isAllowedOrigin(origin);

    // Preflight (only fires if a request ever adds a custom header; simple GETs skip it).
    if (request.method === 'OPTIONS') {
      const headers = new Headers({ Vary: 'Origin' });
      if (allow) {
        headers.set('Access-Control-Allow-Origin', origin);
        headers.set('Access-Control-Allow-Methods', 'GET, HEAD, OPTIONS');
        headers.set('Access-Control-Max-Age', '86400');
      }
      return new Response(null, { status: 204, headers });
    }

    const assetResponse = await env.ASSETS.fetch(request);
    const response = new Response(assetResponse.body, assetResponse);
    // Reflect Origin per-request; delete any platform-default wildcard first so a
    // disallowed origin ends up with no Access-Control-Allow-Origin at all.
    response.headers.append('Vary', 'Origin');
    response.headers.delete('Access-Control-Allow-Origin');
    if (allow) {
      response.headers.set('Access-Control-Allow-Origin', origin);
    }
    if (!response.headers.has('Cache-Control')) {
      response.headers.set('Cache-Control', 'public, max-age=3600');
    }
    return response;
  },
};
"""


def _jsonable(v):
    return v.model_dump() if hasattr(v, "model_dump") else v


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(_BACKEND), "web-data"))
    args = ap.parse_args()

    season = server.season_manager.get_active_season()
    if not season:
        raise SystemExit("No active season — set one before exporting.")
    season_dir = os.path.join(args.out, season)
    os.makedirs(season_dir, exist_ok=True)

    total = 0
    print(f"Exporting season {season} -> {season_dir}")
    for name, fn in CATALOGS.items():
        data = _jsonable(fn())
        path = os.path.join(season_dir, f"{name}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        size = os.path.getsize(path)
        total += size
        print(f"  {name:22s} {size / 1024:9.1f} KB")

    # Entity icons (served via ICON_BASE on web). Copy the bundled icons dir to <out>/icons so the CDN serves
    # /icons/<category>/<file>.webp, matching iconUrl(). ~10 MB of webp; cached per-icon on demand.
    icons_src = os.path.join(server._DATA_ROOT, "images", "icons")
    if os.path.isdir(icons_src):
        icons_dst = os.path.join(args.out, "icons")
        shutil.rmtree(icons_dst, ignore_errors=True)
        shutil.copytree(icons_src, icons_dst)
        n_icons = sum(len(fs) for _, _, fs in os.walk(icons_dst))
        print(f"  icons                  {n_icons} files copied")

    with open(os.path.join(args.out, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump({"season": season}, f)

    # Cloudflare Pages _headers: caching only (ignored under advanced mode, but harmless — the
    # Worker sets Cache-Control itself). CORS is owned by _worker.js below, not here: a static
    # header can only emit one allowed origin (breaking previews/www/local dev) and can't remove
    # the platform default wildcard. Cache for an hour.
    with open(os.path.join(args.out, "_headers"), "w", encoding="utf-8", newline="\n") as f:
        f.write("/*\n  Cache-Control: public, max-age=3600\n")

    # The CORS allowlist Worker (Pages advanced mode). Emitted so a fresh web-data/ export always
    # ships it. Remove any stale functions/ dir from an older export — a _worker.js and functions/
    # together is ambiguous, and only the Worker actually compiles under `wrangler pages deploy`.
    stale_fns = os.path.join(args.out, "functions")
    if os.path.isdir(stale_fns):
        shutil.rmtree(stale_fns, ignore_errors=True)
    with open(os.path.join(args.out, "_worker.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write(_CORS_WORKER_JS)

    # Ship the data terms at the CDN root, so anyone who takes the served files also takes the
    # notice (the terms travel with the data instead of living only in the repo).
    data_license = os.path.join(os.path.dirname(_BACKEND), "DATA-LICENSE.md")
    if os.path.isfile(data_license):
        shutil.copy2(data_license, os.path.join(args.out, "DATA-LICENSE.md"))
    else:
        print("  WARNING: DATA-LICENSE.md not found at repo root — CDN export will omit it")

    print(f"  {'TOTAL':22s} {total / 1024:9.1f} KB  (~{total / 1048576:.1f} MB raw; CDN gzip/brotli -> ~1 MB on the wire)")
    print(f"  manifest.json -> {{'season': '{season}'}}")


if __name__ == "__main__":
    main()
