"""Generate the human-readable verification docs from the JSON source of truth.

`data/verification/*.json` is the single source of truth (the in-app viewer reads it via /api/verification-db).
This tool renders it to markdown so the KB is greppable / linkable / diffable in git:
    docs/verification/README.md   -> the index table (searchable by mechanic + by skill + by status)
    docs/verification/<id>.md     -> one human-readable file per entry

The markdown files are GENERATED ARTIFACTS — do not hand-edit them; edit the JSON and re-run this tool.

Usage:  python backend/tools/gen_verification_docs.py
"""
import json
import os

_BACKEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_REPO = os.path.dirname(_BACKEND)
_SRC_DIR = os.path.join(_REPO, "data", "verification")
_OUT_DIR = os.path.join(_REPO, "docs", "verification")

_STATUS_META = {
    "confirmed":  ("✅", "Confirmed"),
    "partial":    ("🔶", "Partial"),
    "pending":    ("⬜", "Pending"),
    "unverified": ("⚠️", "Unverified"),
    "failed":     ("❌", "Failed"),
}
_STATUS_ORDER = ["confirmed", "partial", "pending", "unverified", "failed"]
_BANNER = "<!-- GENERATED by backend/tools/gen_verification_docs.py — do not hand-edit. Edit data/verification/*.json instead. -->\n\n"


def _load() -> list[dict]:
    entries = []
    if not os.path.isdir(_SRC_DIR):
        return entries
    for fn in sorted(os.listdir(_SRC_DIR)):
        if fn.endswith(".json"):
            with open(os.path.join(_SRC_DIR, fn), encoding="utf-8") as f:
                e = json.load(f)
            e.setdefault("id", os.path.splitext(fn)[0])
            entries.append(e)
    return entries


def _status_label(status: str) -> str:
    icon, label = _STATUS_META.get(status, ("⚠️", "Unverified"))
    return f"{icon} {label}"


def _sort_key(e: dict):
    order = _STATUS_ORDER.index(e.get("status")) if e.get("status") in _STATUS_ORDER else len(_STATUS_ORDER)
    return (order, (e.get("title") or "").lower())


def _entry_md(e: dict) -> str:
    out = [_BANNER, f"# {e.get('title', e['id'])}\n"]
    out.append(f"- **Status:** {_status_label(e.get('status', 'unverified'))}")
    if e.get("skills"):
        out.append(f"- **Skills affected:** {', '.join(e['skills'])}")
    if e.get("tags"):
        out.append(f"- **Mechanic tags:** {', '.join(e['tags'])}")
    if e.get("lastVerified"):
        by = f" by {e['verifiedBy']}" if e.get("verifiedBy") else ""
        out.append(f"- **Last verified:** {e['lastVerified']}{by}")
    if e.get("backlogId"):
        out.append(f"- **Backlog:** `{e['backlogId']}` (see `docs/INGAME_VERIFICATION_BACKLOG.md`)")
    out.append("")
    for title, key in (("Setup", "setup"), ("Raw data points", "dataPoints"),
                       ("Derived / confirmed formula", "formula"),
                       ("Notes / caveats / open questions", "notes")):
        if (e.get(key) or "").strip():
            out.append(f"## {title}\n\n{e[key].strip()}\n")
    if e.get("sources"):
        out.append("## Sources\n")
        out.extend(f"- {s}" for s in e["sources"])
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _index_md(entries: list[dict]) -> str:
    out = [_BANNER, "# Verification Knowledge Base — index\n",
           "Confirmed in-game behavior + the modeled-but-untested backlog. Source of truth: "
           "`data/verification/*.json` (viewable in-app via the main-menu **Verification Database** button). "
           "The pending/untested test queue lives in `docs/INGAME_VERIFICATION_BACKLOG.md`.\n"]
    # Status summary line.
    counts = {}
    for e in entries:
        counts[e.get("status", "unverified")] = counts.get(e.get("status", "unverified"), 0) + 1
    summary = " · ".join(f"{_status_label(s)}: {counts[s]}" for s in _STATUS_ORDER if s in counts)
    out.append(f"**{len(entries)} entries** — {summary}\n")
    out.append("| Mechanic | Skills | Tags | Status | Last verified | File |")
    out.append("|----------|--------|------|--------|---------------|------|")
    for e in sorted(entries, key=_sort_key):
        skills = ", ".join(e.get("skills") or []) or "—"
        tags = ", ".join(e.get("tags") or []) or "—"
        date = e.get("lastVerified") or "—"
        out.append(f"| {e.get('title', e['id'])} | {skills} | {tags} | {_status_label(e.get('status', 'unverified'))} "
                   f"| {date} | [{e['id']}.md]({e['id']}.md) |")
    out.append("")
    return "\n".join(out)


def main() -> None:
    entries = _load()
    os.makedirs(_OUT_DIR, exist_ok=True)
    with open(os.path.join(_OUT_DIR, "README.md"), "w", encoding="utf-8", newline="\n") as f:
        f.write(_index_md(entries))
    for e in entries:
        with open(os.path.join(_OUT_DIR, f"{e['id']}.md"), "w", encoding="utf-8", newline="\n") as f:
            f.write(_entry_md(e))
    print(f"Generated {len(entries)} entries + README.md -> docs/verification/")


if __name__ == "__main__":
    main()
