let BASE = ''
let ipcMode = false
export function getApiBase(): string { return BASE }

// True in the hosted web build (no Electron preload bridge). Desktop-only UI (auto-update, release channel) hides
// when this is set — the web app updates by redeploy + refresh, not electron-updater.
export const IS_WEB = typeof window !== 'undefined' && !window.api?.apiRequest

// ── Static reference-data source (web/CDN) ──────────────────────────────────────────────────────────────
// On the web build, the season-global catalogs are served as static gzipped JSON from a CDN (generated by
// backend/tools/export_web_data.py) instead of hitting the Python backend. Set VITE_STATIC_DATA_BASE to that
// base URL (e.g. https://data.tlibuilder.com). When unset (desktop), everything goes through IPC/HTTP as before.
// Layout: <BASE>/manifest.json -> {season}; <BASE>/<season>/<name>.json per catalog.
const STATIC_DATA_BASE: string = (import.meta.env?.VITE_STATIC_DATA_BASE as string | undefined) || ''
let staticSeason = ''
let webCompute = false   // web build: dispatch backend calls through the Pyodide worker instead of HTTP/IPC
type WebApi = typeof import('../web/pyodideCompute')
let webApi: WebApi | null = null   // loaded once in initApi (web only) so get/post can call it synchronously
// API path -> static filename (the 10 reference catalogs the app loads once at startup).
const STATIC_CATALOGS: Record<string, string> = {
  '/skills': 'skills',
  '/legendary-gear': 'legendary_gear',
  '/legendary-gear-index': 'legendary_gear_index',
  '/craft-base-items': 'craft_base_items',
  '/craft-base-types': 'craft_base_types',
  '/grafts': 'grafts',
  '/hero-traits': 'hero_traits',
  '/hero-memories': 'hero_memories',
  '/conditions': 'conditions',
  '/pact-spirits': 'pact_spirits',
}
function staticCatalogUrl(path: string): string | null {
  if (!STATIC_DATA_BASE || !staticSeason) return null
  const name = STATIC_CATALOGS[path]
  return name ? `${STATIC_DATA_BASE}/${staticSeason}/${name}.json` : null
}

// Host root for bundled entity icons (served by the Python backend at /icons/<category>/<file>.webp).
// Images must load via a real URL even in IPC mode (an <img> can't go through the IPC bridge), so we
// resolve the port here and expose iconUrl() to turn a record's icon_url into a local server URL.
let ICON_BASE = ''
export function iconUrl(category: string, iconRef: string | null | undefined): string | null {
  if (!iconRef || !ICON_BASE) return null
  // Records store a full CDN icon_url; we pair on its basename, which matches the bundled file.
  const clean = iconRef.split('?')[0].split('#')[0]
  const file = clean.substring(clean.lastIndexOf('/') + 1)
  if (!file) return null
  return `${ICON_BASE}/${category}/${file}`
}

const verbose = typeof window !== 'undefined' && window.api?.isVerbose === true
const rlog = (...args: unknown[]) => { if (verbose) console.log('[api]', ...args) }
const rerr = (...args: unknown[]) => { if (verbose) console.error('[api]', ...args) }

async function probePort(port: number): Promise<boolean> {
  rlog(`probePort(${port}) — fetching /api/trees`)
  try {
    const res = await fetch(`http://127.0.0.1:${port}/api/trees`, {
      signal: AbortSignal.timeout(800),
    })
    rlog(`probePort(${port}) — status ${res.status}, ok=${res.ok}`)
    return res.ok
  } catch (e) {
    rlog(`probePort(${port}) — failed: ${e}`)
    return false
  }
}

export async function initApi(): Promise<void> {
  rlog('initApi — start, window.api defined:', typeof window !== 'undefined' && 'api' in window)
  // Resolve the static-data season from the CDN manifest (web build). Catalog reads then come from the CDN;
  // anything else still uses IPC/HTTP below.
  if (STATIC_DATA_BASE) {
    try {
      const m = await (await fetch(`${STATIC_DATA_BASE}/manifest.json`)).json()
      staticSeason = m.season || ''
      rlog(`initApi — static data base ${STATIC_DATA_BASE}, season ${staticSeason}`)
      // Web build (no Electron IPC): run compute in the Pyodide worker. Kick off its load in the background;
      // engineStats awaits readiness on first use.
      if (!window.api?.apiRequest && staticSeason) {
        webCompute = true
        webApi = await import('../web/pyodideCompute')
        webApi.initPyodideCompute(STATIC_DATA_BASE, staticSeason)
          .catch(e => rerr(`initApi — pyodide backend init failed: ${e}`))
      }
    } catch (e) {
      rerr(`initApi — failed to load static manifest from ${STATIC_DATA_BASE}: ${e}`)
    }
  }
  // Web build: catalogs come from the CDN and compute from the Pyodide worker — there's no local backend to
  // find, so skip the IPC/port-scan paths (which would otherwise spam CSP-blocked fetches to 127.0.0.1).
  if (webCompute) {
    ICON_BASE = `${STATIC_DATA_BASE}/icons`   // entity icons served from the CDN (export_web_data copies them)
    rlog('initApi — web mode: static catalogs + Pyodide compute; no backend')
    return
  }
  if (window.api?.apiRequest) {
    ipcMode = true
    rlog('initApi — Electron IPC path: waiting for port readiness via getPythonPort')
    const port = await window.api.getPythonPort()
    ICON_BASE = `http://127.0.0.1:${port}/icons`
    rlog(`initApi — IPC ready, ipcMode=true, ICON_BASE: ${ICON_BASE}`)
    return
  }
  rlog('initApi — browser path: scanning ports 8765-8774')
  for (let port = 8765; port <= 8774; port++) {
    if (await probePort(port)) {
      BASE = `http://127.0.0.1:${port}/api`
      ICON_BASE = `http://127.0.0.1:${port}/icons`
      rlog(`initApi — found server on port ${port}, BASE: ${BASE}`)
      return
    }
  }
  BASE = 'http://127.0.0.1:8765/api'
  ICON_BASE = 'http://127.0.0.1:8765/icons'
  rerr(`initApi — no server found on 8765-8774, defaulting BASE to: ${BASE}`)
}

async function get<T>(path: string, retries = 4): Promise<T> {
  // Web build: serve reference catalogs from the static CDN (gzipped JSON) instead of the backend.
  const staticUrl = staticCatalogUrl(path)
  if (staticUrl) {
    rlog(`GET (static) ${staticUrl}`)
    const res = await fetch(staticUrl)
    if (!res.ok) throw new Error(`GET ${staticUrl} → ${res.status}`)
    return res.json()
  }
  if (webCompute && webApi) return webApi.webApiRequest<T>('GET', `/api${path}`)
  if (ipcMode) {
    rlog(`GET (IPC) ${path}`)
    const result = await window.api!.apiRequest('GET', path) as { ok: boolean; status: number; data: T }
    if (!result.ok) throw new Error(`GET ${path} → ${result.status}`)
    return result.data
  }
  const url = `${BASE}${path}`
  for (let attempt = 0; attempt <= retries; attempt++) {
    rlog(`GET ${url} — attempt ${attempt + 1}/${retries + 1}`)
    try {
      const res = await fetch(url)
      rlog(`GET ${url} — status ${res.status}`)
      if (!res.ok) throw new Error(`GET ${path} → ${res.status}`)
      return await res.json()
    } catch (e) {
      const isNetwork = e instanceof TypeError
      rerr(`GET ${url} — error (isNetwork=${isNetwork}): ${e}`)
      if (!isNetwork || attempt === retries) throw e
      const delay = 400 * (attempt + 1)
      rlog(`GET ${url} — retrying in ${delay}ms`)
      await new Promise(r => setTimeout(r, delay))
    }
  }
  throw new Error(`GET ${path} failed`)
}

async function post<T>(path: string, body: unknown): Promise<T> {
  if (webCompute && webApi) return webApi.webApiRequest<T>('POST', `/api${path}`, body)
  if (ipcMode) {
    rlog(`POST (IPC) ${path}`)
    const result = await window.api!.apiRequest('POST', path, body) as { ok: boolean; status: number; data: T }
    if (!result.ok) throw new Error(`POST ${path} → ${result.status}`)
    return result.data
  }
  const url = `${BASE}${path}`
  rlog(`POST ${url}`)
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(15000),
  })
  rlog(`POST ${url} — status ${res.status}`)
  if (!res.ok) throw new Error(`POST ${path} → ${res.status}`)
  return res.json()
}

async function put<T>(path: string, body: unknown): Promise<T> {
  if (webCompute && webApi) return webApi.webApiRequest<T>('PUT', `/api${path}`, body)
  if (ipcMode) {
    rlog(`PUT (IPC) ${path}`)
    const result = await window.api!.apiRequest('PUT', path, body) as { ok: boolean; status: number; data: T }
    if (!result.ok) throw new Error(`PUT ${path} → ${result.status}`)
    return result.data
  }
  const url = `${BASE}${path}`
  rlog(`PUT ${url}`)
  const res = await fetch(url, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(15000),
  })
  rlog(`PUT ${url} — status ${res.status}`)
  if (!res.ok) throw new Error(`PUT ${path} → ${res.status}`)
  return res.json()
}

async function del<T>(path: string, body?: unknown): Promise<T> {
  if (webCompute && webApi) return webApi.webApiRequest<T>('DELETE', `/api${path}`, body)
  if (ipcMode) {
    rlog(`DELETE (IPC) ${path}`)
    const result = await window.api!.apiRequest('DELETE', path, body) as { ok: boolean; status: number; data: T }
    if (!result.ok) throw new Error(`DELETE ${path} → ${result.status}`)
    return result.data
  }
  const url = `${BASE}${path}`
  rlog(`DELETE ${url}`)
  const res = await fetch(url, {
    method: 'DELETE',
    headers: body ? { 'Content-Type': 'application/json' } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  })
  rlog(`DELETE ${url} — status ${res.status}`)
  if (!res.ok) throw new Error(`DELETE ${path} → ${res.status}`)
  return res.json()
}

// ── Share service ────────────────────────────────────────────────────────────
// The build-code share service is a PUBLIC host, separate from the local Python
// backend. Share calls never go through the local backend or Electron IPC —
// they are plain fetches to SHARE_BASE. The base URL is configurable at build
// time via the Vite env var VITE_SHARE_BASE_URL; it falls back to production.

const _shareEnv = (import.meta as unknown as { env?: Record<string, string | undefined> }).env
const SHARE_BASE = (_shareEnv?.VITE_SHARE_BASE_URL ?? 'https://api.tlibuilder.com').replace(/\/+$/, '')

export function getShareBase(): string { return SHARE_BASE }

async function postToShareService<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${SHARE_BASE}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(15000),
  })
  if (!res.ok) throw new Error(`POST ${path} → ${res.status}`)
  return res.json() as Promise<T>
}

const MAX_SHARE_CODE_BYTES = 512 * 1024 // 512 KB — more than enough for any build code

async function getFromShareService(path: string): Promise<string> {
  // The share service returns the raw tli1_ code as text/plain.
  const res = await fetch(`${SHARE_BASE}${path}`, {
    signal: AbortSignal.timeout(15000),
  })
  if (!res.ok) throw new Error(`GET ${path} → ${res.status}`)
  const len = Number(res.headers.get('content-length') ?? 0)
  if (len > MAX_SHARE_CODE_BYTES) throw new Error('Shared build code exceeds size limit')
  // No Content-Length fallback: buffers entire response before rejecting — acceptable
  // given threat model; a streaming reader would be needed to truly bound a hostile server.
  const text = await res.text()
  if (text.length > MAX_SHARE_CODE_BYTES) throw new Error('Shared build code exceeds size limit')
  return text
}

export interface TreeSlot {
  treeName: string
  nodeStates: Record<string, number>
  coreTalentSelections?: Record<string, string>  // slot index → selected talent id
}

export interface SavedSlateSlot {
  slotType: 'magic' | 'rare' | 'legendary'
  maxType: 'magic' | 'rare' | 'legendary'
  canBeCore: boolean
  isCore: boolean
  selectedNodeId: string | null
  selectedCoreKey: string | null
  coreName: string | null
  effects: string[]
  // The selected node's talent type (Micro/Medium/Legendary Medium) — drives the copy-slate "Medium
  // talents" filter (Space Rift / Residence of Stars).
  nodeType?: string | null
}

export interface SavedSlate {
  id: string
  templateId?: string
  kind: string
  cells: [number, number][]
  orientationIndex: number
  shapeIndex: number
  anchor: [number, number]
  slots: SavedSlateSlot[]
  treeType?: string
  mothDirection?: string
}

// A configured slate kept in the build's saved-slates inventory (no board placement) — re-placeable.
export interface SlateTemplate {
  id: string
  kind: string
  orientationIndex: number
  shapeIndex: number
  slots: SavedSlateSlot[]
  treeType?: string
  mothDirection?: string
}

// ── Prisms ──────────────────────────────────────────────────────────────────
// A prism item from the imported catalog (GET /ethereal-prism). Inverse Image carries roll_ranges.
export interface PrismCatalogItem {
  name: string
  kind: 'inverse_image' | 'ethereal_prism'
  icon_url: string
  tags: string[]
  detail: string[]
  implicit: string[]
  roll_ranges?: { micro: [number, number]; medium: [number, number]; legendary: [number, number] }
}
// ── Ethereal-Prism crafting catalog (the enriched `catalog` field of GET /ethereal-prism) ───────────
export type PrismRarity = 'rare' | 'legendary'
export interface PrismImplicit {
  kind: 'replace' | 'amplify' | 'add_choice'
  text?: string         // replace/amplify: the fixed implicit line
  options?: string[]    // add_choice (Haze): the 10 selectable "Adds an additional effect…" lines
}
export interface EtherealCatalogItem {
  name: string
  short_name: string
  kind: 'ethereal_prism'
  icon_url: string
  tags: string[]
  detail: string[]
  rarities: PrismRarity[]
  default_rarity: PrismRarity
  tint_when_rare: boolean   // apply the purple CSS filter for the rare variant (named prisms only)
  implicit: PrismImplicit
  replace_description: string   // replace prisms: the replacement Core Talent's effect text (from the glossary)
}
export interface AreaSizeAffix { modifier: string; cols: number; rows: number }
export interface MiddleAffix {
  modifier: string
  tier: 'micro' | 'medium' | 'legendary' | ''
  scaled: boolean   // true = the ×1.75 Phantasmagoria-only variant; false = base (every other prism)
}
export interface AdvancedAffix {
  modifier: string
  kind: 'over_alloc' | 'ignore_prereq' | 'conditional'
  tier?: 'micro' | 'medium' | 'legendary' | ''
  count?: number
}
export interface DoNotReplaceAffix { modifier: string; penalty: string }
export interface EtherealCatalog {
  items: EtherealCatalogItem[]
  area_size: AreaSizeAffix[]
  middle: MiddleAffix[]
  advanced: AdvancedAffix[]
  do_not_replace: Record<string, DoNotReplaceAffix[]>   // keyed by prism short_name
  penalties: string[]
}
export interface PrismCatalog {
  season: string | null
  items: PrismCatalogItem[]
  base_affixes: string[]
  random_affixes: { modifier: string; type: string }[]
  catalog?: EtherealCatalog
}
// The three Inverse Image affix rolls (% multipliers; −100 = off/untempered).
export interface PrismRolls {
  micro: number
  medium: number
  legendary: number
}
// An Ethereal Prism's crafted configuration (implicit + the 1–3 random-affix slots). Distinct from Inverse
// Image's `rolls`. boxCols/boxRows are derived from the chosen area-size affix for placement geometry.
export interface EtherealConfig {
  shortName: string
  rarity: PrismRarity
  implicit: string             // resolved implicit line (replace/amplify text, or Haze's chosen add option)
  tintWhenRare: boolean        // mirror of the catalog item flag (icon rendering)
  areaSize?: string            // chosen Slot-1 area-size modifier
  boxCols?: number             // box footprint derived from areaSize
  boxRows?: number
  middle?: string              // chosen Slot-2 middle-tier modifier
  advanced?: string            // chosen Slot-3 advanced/do-not-replace modifier (legendary only)
}
// A crafted prism kept in the build's prism inventory (no tree placement) — re-placeable, like SlateTemplate.
// `rolls` is used by Inverse Image; `ethereal` by Ethereal Prisms.
export interface CraftedPrism {
  id: string
  kind: 'inverse_image' | 'ethereal_prism'
  name: string
  iconUrl: string
  rolls: PrismRolls
  ethereal?: EtherealConfig
}
// A prism installed on a tree. anchorCol/anchorRow = the node it sits on; boxAllocations = points spent in the
// reflected box (kept OUT of the DPS path in Plan 1), keyed by the existing node id at each reflected position.
export interface PlacedPrism {
  id: string
  templateId: string
  kind: 'inverse_image' | 'ethereal_prism'
  name: string
  iconUrl: string
  rolls: PrismRolls
  ethereal?: EtherealConfig
  treeName: string
  anchorCol: number
  anchorRow: number
  boxAllocations: Record<string, number>
}

export interface Build {
  id?: string
  name: string
  slots: (TreeSlot | null)[]
  slates?: SavedSlate[]
  slateInventory?: SlateTemplate[]
  prisms?: PlacedPrism[]
  prismInventory?: CraftedPrism[]
  conditionState?: Record<string, number | boolean>
  // Legacy fields — present on builds saved before the conditionState unification.
  // Read-only: never written by the current client; migrated to conditionState on load.
  conditions?: string[]
  conditionValues?: Record<string, number>
  gear?: EquippedGearItem[]
  skills?: EquippedSkill[]
  characterLevel?: number
  traitId?: string | null
  traitLevel?: number          // legacy field — kept for loading old saves
  traitSlotLevels?: number[]   // [base, lv45, lv60, lv75], each 1–5
  advancedTraitSelections?: string[]
  traitSkillSupports?: EquippedSupportSkill[]   // supports socketed into the Holy Domain trait skill slot
  heroMemories?: (unknown | null)[]
  pactSpirits?: (unknown | null)[]
  fates?: Record<string, InstalledFate>           // pact fates keyed by "<spiritSlotIdx>:<nodeDataIdx>"
  undetermined?: (UndeterminedFate | null)[]      // one per spirit slot
  notes?: string
  customMods?: string[]
}

export interface TreeNode {
  id: string
  column: number
  row: number
  max_points: number
  node_type: string
  current_points: number
  effects: string[]
  icon_url?: string | null   // CDN url; render via iconUrl('talent_tree', icon_url) → bundled webp
}

// Static per-line resolution for a core-talent effect (from /api/tree) — drives the NYI/Inactive badges
// on any tree regardless of selection. kind 'stat'|'override' resolve; 'deferred'|'unresolved' do not.
export interface CoreTalentEffectStatus {
  resolved: boolean
  kind: 'stat' | 'override' | 'deferred' | 'unresolved'
  stat_keys: string[]
}

export interface CoreTalentSlotOption {
  id: string
  name: string
  effects: string[]
  icon_url?: string | null                   // render via iconUrl('talent_tree', icon_url) → bundled webp
  effect_status?: CoreTalentEffectStatus[]   // aligned 1:1 with effects
}

export interface CoreTalentSlot {
  threshold: number
  options: CoreTalentSlotOption[]
  selected_id: string | null
}

export interface TreeData {
  name: string
  nodes: TreeNode[]
  connections: { from: string; to: string }[]
  core_talent_slots: CoreTalentSlot[]
  node_prefix: string
}

export interface NodeEditData {
  id: string
  column: number
  row: number
  node_type: string
  max_points: number
}

export interface ModPoolEntry {
  stat: string
  display_name: string
  unit: string
  micro_increment: number
  medium_increment: number
  legendary_increment: number
  node_types: string[]
}

export interface SnapshotModifier {
  text: string
}

export interface StatRecipe {
  stat: string
  rank1: number
  values: number[]
  display_name: string
}

export interface TiedCandidate {
  stat: string
  display_name: string
  score: number
}

export interface UnresolvedStat {
  tree: string
  node_type: string
  text: string
  reason?: 'ambiguous' | 'unmatched' | 'multi_text' | 'conditional'
  tied?: TiedCandidate[]
}

export interface SnapshotStatus {
  exists: boolean
  source_file: string | null
  generated_at: string | null
}

export interface NodeTypeFilterMeta {
  generated_at: string
  snapshot_source: string
  matched: number
  ambiguous: number
  unmatched: number
  conditional: number
}

export interface FilterOverride {
  stat: string
  example: string
}

export interface RebuildFilterResult {
  _meta: NodeTypeFilterMeta
  stats: Record<string, string[]>
  unresolved: UnresolvedStat[]
  matched_texts: Record<string, string[]>
}

export interface TalentStat {
  text: string
  max_divinity_effect?: true
}

export interface TalentNode {
  node_type: string
  stats: TalentStat[]
}

export interface CoreTalentEntry {
  name: string
  stats: TalentStat[]
}

export interface NewGodTalent {
  name: string
  stats: TalentStat[]
}

export interface TreeSnapshot {
  nodes: TalentNode[]
  core_talents: CoreTalentEntry[]
}

export interface TalentSnapshot {
  generated_at: string
  source_file: string
  trees: Record<string, TreeSnapshot>
  new_god_talents: NewGodTalent[]
}

export interface SlateModifierOption {
  nodeId: string
  treeName: string
  nodeType: string
  effects: string[]
}

export interface CoreTalentOption {
  key: string       // "{treeName}:{display_name_key}"
  treeName: string
  name: string
  effects: string[]
}

export interface SlatePool {
  magic: SlateModifierOption[]
  rare: SlateModifierOption[]
  legendary: SlateModifierOption[]
  core: CoreTalentOption[]
}

export interface ConditionDef {
  key: string
  label: string
  category?: string
  value_type: 'boolean' | 'numeric'
  numeric_min?: number
  numeric_max?: number | null
  min_base?: number
  min_from_stat?: string | null
  max_base?: number
  max_from_stat?: string | null
  unit?: string
  default_value?: number
  default_bool?: boolean
  visible?: boolean
  is_derived?: boolean
  source?: string
  trait_id?: string | null   // hero-trait conditions: shown only when this trait is selected (or Show all)
}

export interface ConditionSourceEntry {
  text: string
  sources: string[]
  affix_count: number
  expression: Record<string, unknown> | string | null
  mapped: boolean
}

export interface ConditionDefsResponse {
  conditions: ConditionDef[]
  derived_keys: Record<string, string>
}

export interface StatSource {
  source_type: string
  label: string
  text: string
  source_name?: string | null  // display name of the origin (item/spirit/memory/support); drives "Source Name"
  amount: number
  points: number  // allocated points; >1 for multi-rank talent nodes
  slot?: number | null   // set on slot-local (skill-specific) sources; null/absent = character-wide
  scope?: string | null  // skill-tag scope ("attack"/"spell"/…) when restricted
}

export interface StatEntry {
  display_name: string
  category: string
  unit: string    // "" | "%"
  total: number
  sources: StatSource[]
  // Slot-local (skill-specific) contributions — supports + skill self-buffs that fold into a skill slot's
  // offense, NOT into `total`/`sources`. Surfaced separately so the breakdown can show them.
  slot_sources?: StatSource[]
}

export interface SkillEngineInput {
  skill_id: string
  level: number
}

export interface SkillSlotInput {
  slot: number      // 1–5 active, 6–9 passive
  skill_id: string
  level: number
  enabled?: boolean // default true; disabled skills (and their supports + sourced buffs/debuffs) drop out
}

// A support attached to a skill, sent to the engine so it can resolve the support's
// damage lines (rank scales the universal line; level/tier scales the specific lines).
export interface AttachedSupportInput {
  item_id: string
  skill_type: string
  rank?: number
  level: number
  specific_rolls?: Record<string, number>
  slot?: number     // the host skill's slot (default 1); contributions are local to this slot
  enabled?: boolean // default true; disabled supports drop out of the calc
}

export interface SkillSlotSummary {
  slot: number
  skill_id: string
  skill_name: string
  level: number
  effective_level: number
  supported: boolean
}

export interface HitFormResult {
  name: string
  effectiveness_pct: number
  form_type: 'additive' | 'exclusive'
  proc_chance: number
  damage_by_type: Record<string, number>
  avg_hit_pre_crit: number
  avg_hit_with_crit: number
  dps_contribution: number
  dps_vs_target: number
  hit_min_by_type: Record<string, number>
  hit_max_by_type: Record<string, number>
  // This form's effective occurrences/sec (rate × proc). Channeled forms differ: a "continuous" form fires
  // every use, a "burst" form once per RESET cycle. hits_per_fire = projectiles/blades per occurrence.
  fires_per_sec: number
  hits_per_fire: number
  shotgun_falloff: number   // same-target Shotgun Effect falloff coefficient (each subsequent hit −this)
  shotgun_mult: number      // total per-occurrence shotgun multiplier (1 + (hits−1)×(1−falloff))
  base_min_by_type: Record<string, number>   // this form's intrinsic base (multi-form spells)
  base_max_by_type: Record<string, number>
}

export interface OffenseResult {
  skill_name: string
  supported: boolean   // false = NYI; when false no other fields are meaningful
  effective_level: number
  hit_forms: HitFormResult[]
  crit_chance: number
  crit_multiplier: number
  steep_strike_chance: number
  attacks_per_second: number
  base_cast_time: number
  total_dps: number
  total_dps_vs_target: number
  // Same-target shotgun (e.g. Chain Lightning Merge+Web): extra same-target hits per cast at falloff. Scales
  // total DPS only — applied to total_dps(_vs_target) but NOT to per-form dps_vs_target — so the per-form /
  // per-type breakdown must multiply by this to reconcile to 100%. 1.0 when no shotgun.
  cast_multiplier: number
  shotgun_hits: number
  // Tangle mode (spell cast by N attached tangles, not the player). 0 / 1.0 when not tangled. tangle_count and
  // tangle_enhancement fold into the DPS totals like cast_multiplier; the rest are display-only mechanic stats.
  tangle_count: number
  tangle_enhancement: number
  tangle_mult: number          // total Tangle delivery multiplier folded into total_dps (= count; 1.0 if untangled)
  tangle_placeable: number
  tangle_inactivated: number
  tangle_duration: number
  tangle_attach_range: number
  // Spell Burst mode (an eligible Spell cast at full charge consumes M stacks and auto-recasts the spell M
  // times; the triggering cast also counts → casts_per_burst = M + 1). The charge is a server-timed whole-tick
  // countdown (hard-rounded breakpoints), so charge speed only helps at integer-tick crossings. spell_burst_mult
  // folds into total_dps like cast_multiplier; 0 / 1.0 when not bursting.
  spell_burst_count: number            // Max Spell Burst (M); 0 = not bursting
  spell_burst_casts_per_burst: number  // M + 1
  spell_burst_charge_ticks: number     // whole-tick charge period (ceil(30 × charge time))
  spell_burst_charge_time: number      // seconds to full charge (after Surging)
  spell_burst_charge_factor: number    // total Spell Burst Charge Speed multiplier ((1+Σinc)×Π(1+add))
  spell_burst_charge_inc: number       // Σ Spell Burst Charge Speed INCREASED only (matches in-game; Solid River gate)
  spell_burst_charge_to_next_inc: number   // charge-speed Increased % for the next bursts/sec breakpoint (0 = none found)
  spell_burst_cast_to_next_inc: number     // cast-speed Increased % for the next bursts/sec breakpoint, manual (0 = none/charge-limited)
  spell_burst_next_breakpoint_ticks: number // charge-tick count of the next charge-speed breakpoint (0 = none)
  spell_burst_rate: number             // bursts per second (≤ 30)
  spell_burst_mult: number             // total damage multiplier from bursting (folded into total_dps)
  spell_burst_auto: boolean            // auto-trigger (instant at full charge) vs manual (cast-gated)
  spell_burst_auto_source: string      // what drives auto-trigger (e.g. Burst Activation); "" = manual
  // Burst / non-burst DPS split. Manual = combined (you cast between bursts → non-burst > 0); auto = burst-only
  // (non-burst = 0). spell_burst_dps + non_spell_burst_dps = total_dps (same for the _vs_target pair).
  spell_burst_dps: number
  spell_burst_dps_vs_target: number
  non_spell_burst_dps: number
  non_spell_burst_dps_vs_target: number
  // Channeled mode (held skill gaining 1 stack/use; RESET dumps at max + fires a burst form). All 0 / "" when
  // not channeled. The continuous form fires every use; the burst form at channeled_burst_rate. Stacks are
  // display-only (steady state = the cap).
  channeled_max_stacks: number          // cap after +Max Channeled Stacks (0 = not channeled)
  channeled_min_stacks: number          // Min Channeled Stacks (first round from 0 gains 1 + this)
  channeled_stacks: number              // display steady-state stacks (= cap for a sustained channel)
  channeled_rounds_per_cycle: number    // uses per RESET cycle = max(1, max − min)
  channeled_burst_rate: number          // reset-burst occurrences/sec (= aps / rounds_per_cycle)
  channeled_behavior: string            // "reset" | "refresh" | "" (not channeled)
  channeled_attack_frequency: number    // persistent-entity strike rate (Howling Gale's Gale); 0 = N/A
  projectile_count: number              // projectiles of the projectile-scaling form (Icy Blade); 0 = N/A
  // Combined per-type ENEMY damage multiplier on outgoing damage: (1−armor)(1−resist) × enemy vulnerability
  // (Paralysis/Numbed/Frostbite/curses/…). Only types this skill deals are present. 1.0 = neutral.
  enemy_mult_by_type?: Record<string, number>
  // Multistrike (attack skills): per-cast delivery multiplier from auto-repeats with increasing damage + the
  // +20% repeat attack speed. mult 1.0 / chance 0 when not multistriking.
  multistrike_chance?: number          // total chance (fraction; 1.16 = 116%)
  multistrike_avg_count?: number       // expected attacks per chain = 1 + chance
  multistrike_increment?: number       // effective per-stack increment (base × (1 + additional))
  multistrike_max_count?: number       // longest possible chain (Max Multistrike Count)
  multistrike_mult?: number            // delivery multiplier folded into total_dps
  multistrike_repeat_aps?: number      // attack rate during repeats (base aps × the +20%-increased factor)
  multistrike_chain?: { count: number; prob: number }[]   // chain-length distribution
  nyi: string[]
  weapon_attack_speed: number
  weapon_aps_gear: number
  weapon_aps_mh: number
  weapon_crit_rating_flat: number
  weapon_csr_gear: number
  weapon_csr_mh: number
  base_csr: number
  flat_dmg_min: Record<string, number>
  flat_dmg_max: Record<string, number>
  base_dmg_min: Record<string, number>
  base_dmg_max: Record<string, number>
  type_inc: Record<string, number>
  type_add: Record<string, number>
  above_max_mult: number
  generic_inc: number
  generic_add: number          // INCLUDES the main-stat Damage Bonus below
  main_stat_damage_bonus: number  // fraction (0.255 = +25.5%) from the skill's main-stat attributes
  main_stats: string[]            // attributes summed (e.g. ['dexterity','intelligence'])
  skill_tags: string[]
  skill_area_inc: number
}

export interface DefenseResult {
  max_life: number
  max_mana: number
  max_energy_shield: number
  // Mana/Life sealing & reservation (defaults: full pools when nothing seals).
  sealed_mana?: number
  unsealed_mana?: number
  sealed_life?: number
  unsealed_life?: number
  sealed_mana_compensation?: number
  insufficient_mana?: boolean
  insufficient_life?: boolean
  armor: number
  evasion: number
  fire_resist: number
  cold_resist: number
  lightning_resist: number
  erosion_resist: number
  fire_resist_raw: number
  cold_resist_raw: number
  lightning_resist_raw: number
  erosion_resist_raw: number
  fire_resist_max: number
  cold_resist_max: number
  lightning_resist_max: number
  erosion_resist_max: number
  life_flat: number
  life_inc: number
  life_additional: number
  mana_flat: number
  mana_inc: number
  mana_additional: number
  es_flat: number
  es_inc: number
  es_additional: number
  armor_flat: number
  armor_inc: number
  armor_additional: number
  evasion_flat: number
  evasion_inc: number
  evasion_additional: number
  // Armour → mitigation % and Evasion → evade chance (fractions), vs the calc target.
  armor_phys_mitigation: number
  armor_nonphys_mitigation: number
  attack_evade_chance: number
  spell_evade_chance: number
  // Block (additive chance, display-only for now) + damage avoidance (fractions).
  attack_block_chance: number
  spell_block_chance: number
  block_ratio: number                // base 30% + mods, clamped to the upper limit
  block_ratio_upper_limit: number    // base 60%, raisable to 80%
  dmg_avoid_chance: number
  nyi: string[]
}

export interface BlessingEffect { stat: string; per_stack: number; total: number; text: string }
export interface BlessingSummary {
  type: string
  label: string
  stacks: number
  max: number
  overridden: boolean
  effects: BlessingEffect[]
}

export interface CustomModStatus {
  text: string
  resolved: boolean
  stat_display: string | null
}

export interface ResolveModResult {
  stat_key: string
  amount: number
  text: string
  display_name: string
}

export interface ResolveModResponse {
  text: string
  resolved: ResolveModResult[]
}

export interface StatSheetResponse {
  stats: Record<string, StatEntry>
  condition_maximums: Record<string, number>
  clamp_report: Record<string, { requested: number; applied: number }>
  offense?: OffenseResult | null
  defense?: DefenseResult | null
  custom_mod_statuses?: CustomModStatus[]
  // Gear affix/implicit texts the frontend couldn't resolve, resolved (or reported) backend-side so
  // nothing is silently dropped. resolved:false → still unmodeled (surface it, don't hide it).
  gear_mod_statuses?: CustomModStatus[]
  // Pact-spirit / hero-memory effect resolution (unified resolver, server-side). resolved:false → NYI.
  spirit_mod_statuses?: CustomModStatus[]
  memory_mod_statuses?: CustomModStatus[]
  // Per-effect resolution for granted core talents (roadmap #4) — drives the core-talent NYI badges.
  // kind: 'stat' | 'override' (applied) | 'deferred' | 'unresolved' (captured, not applied).
  core_talent_statuses?: CoreTalentStatus[]
  skill_slots?: SkillSlotSummary[]
  // Per-active-slot offense ({slot: OffenseResult}); headline `offense` is the main slot. Lets the UI
  // eventually show each setup's DPS independently. Additive — not consumed yet.
  slot_offense?: Record<string, OffenseResult> | null
  // Stat keys the engine actually READ for this build (offense/defense/derive/aggregator). A resolved
  // modifier whose mapped stat is here → "Consumed" (green badge).
  consumed_stats?: string[]
  // Maximal set of stats the engine can EVER read (all skills/tags). Lets the badge tell "Inactive"
  // (modeled, just not for your selected skill — in here, not in consumed_stats) apart from "Unconsumed"
  // (engine never reads it — resolved but not in here). Global + cached server-side.
  consumable_universe?: string[]
  // Calculation-target (dummy) armor/resist, base + effective after this build's penetration (values are
  // damage-REDUCTION fractions; negative effective = the target is amplified), plus active enemy debuffs.
  target_stats?: TargetStats | null
  // Numbed ailment box: base per-stack (incl. Conductive), the increased/additional Numbed Effect pools,
  // per-stack duration, effective stacks, the enemy Lightning-taken total, and (real uptime mode) the
  // Feline Figure application rate + the FF-inflicted Numbed duration that produced the steady state.
  numbed?: NumbedInfo | null
  // Per equipped aura/Focus passive: the buff lines it grants (already scaled by Aura Effect + interpolated to
  // level) + the applied Aura Effect + any buff lines not yet modeled (NYI).
  auras?: AuraSummary[]
  aura_statuses?: { skill_id: string; text: string; resolved: boolean; kind: string }[]
  // Per equipped empower skill: the Euphoria buff lines it grants (scaled by Empower Effect + interpolated) + the
  // applied Empower Effect + NYI lines; statuses; and settable per-empower buff-stack conditions (sliders).
  empowers?: EmpowerSummary[]
  empower_statuses?: { skill_id: string; text: string; resolved: boolean; kind: string }[]
  empower_stack_conditions?: { key: string; label: string; max: number }[]
  // Per active curse: Curse Effect / limit / debuff value (scaled) + applied flag; per-curse meta (base stats +
  // NYI lines) keyed by skill_id; NYI statuses; and the over-limit conflict that drives the resolution dropdown.
  curses?: CurseSummary[]
  curse_meta?: Record<string, CurseMeta>
  curse_statuses?: { skill_id: string; text: string; resolved: boolean; kind: string }[]
  curse_conflict?: CurseConflict | null
  // General build warnings/diagnostics (e.g. a curse amplifying a damage type the build doesn't deal).
  warnings?: { kind: string; text: string }[]
  // Mana/Life sealing: totals (sealed/unsealed pools, insufficient flags) + per-skill seal breakdowns.
  reservation?: ReservationResult | null
}

export interface ReservationSummary {
  skill_id: string
  name: string
  slot: number | null
  base_fraction: number
  pool_max: number          // Max of the pool sealed (Max Mana, or Max Life when Seal-Converted)
  support_mults: { name: string; mult: number }[]
  comp_sources: { label: string; value: number; kind: 'increased' | 'additional' }[]
  compensation: number       // net = (1+Σinc)×(1+Σadd) − 1
  comp_increased: number     // Σ increased Sealed Mana Compensation (this skill)
  comp_additional: number    // Σ additional Sealed Mana Compensation (this skill)
  amount: number
  pool: 'mana' | 'life'
}
export interface ReservationResult {
  max_mana: number
  sealed_mana: number
  unsealed_mana: number
  max_life: number
  sealed_life: number
  unsealed_life: number
  sealed_mana_compensation: number
  insufficient_mana: boolean
  insufficient_life: boolean
  per_skill: ReservationSummary[]
}

export interface AuraGrant { stat: string; base: number; amount: number; text: string; per_stack?: boolean; is_aura_effect?: boolean }
export interface AuraSummary {
  skill_id: string
  name: string
  level: number
  aura_effect_inc: number
  granted: AuraGrant[]
  nyi: string[]
  review?: string[]   // modifiers applied but whose per-level scaling couldn't be verified vs the Lv1 anchor
  stack_condition?: string | null   // settable numeric condition key for this aura's buff stacks
  max_stacks?: number | null
}

export interface EmpowerGrant { stat: string; base: number; amount: number; text: string; per_stack?: boolean; is_empower_effect?: boolean }
export interface EmpowerSummary {
  skill_id: string
  name: string
  level: number
  empower_effect_inc: number        // applied Empower Skill Effect ((1+inc)×(1+additional) − 1)
  granted: EmpowerGrant[]
  nyi: string[]
  review?: string[]
  stack_condition?: string | null
  max_stacks?: number | null
}

export interface CurseSummary {
  skill_id: string
  curse_name: string
  level: number
  stat_key: string | null     // which {type}_curse_taken / hit_curse_taken pool (null = NYI curse)
  modeled: boolean
  source_label: string        // where this curse comes from (slot N / gear item)
  base_amount: number         // the curse's "+X% additional damage taken" line, pre-Curse-Effect (fraction)
  scaled_amount: number       // after Curse Effect (Base × (1 + inc) × (1 + additional))
  curse_effect_inc: number
  curse_effect_additional: number
  limit: number
  n_active: number
  applied: boolean            // false when suppressed by an unresolved over-limit conflict
}
export interface CurseMeta {
  curse_name: string
  level: number
  type: string | null
  base_amount: number
  modeled: boolean
  source_label: string
  nyi: string[]
  base_stats: { mana_cost?: number | string | null; cast_speed?: number | string | null; cooldown?: number | string | null; duration?: number | null }
}
export interface CurseConflict {
  limit: number
  active: { name: string; source: string; sel_key: string }[]
  resolved: boolean
}

export interface TargetDebuff {
  name: string
  scope: string       // which damage it amplifies, e.g. "All damage" / "Spell damage" / "Lightning damage"
  taken_inc: number   // damage-taken increase fraction (0.15 = +15% taken)
  stacks?: number
}

export interface TargetStats {
  source?: string   // where the base values come from (e.g. "Training dummy")
  armor: { base_phys: number; base_nonphys: number; effective_phys: number; effective_nonphys: number; pen?: number }
  // base → (+reduction) resist → (−pen) effective. reduction = enemy resistance debuff; pen = ignored at hit.
  resists: Record<string, { base: number; reduction?: number; pen?: number; resist?: number; effective: number }>
  debuffs: string[]   // legacy flat list (kept for back-compat)
  debuff_details?: TargetDebuff[]
  // Raw penetration totals (fractions; reduction deltas).
  pen?: { armor: number; all_resistance_reduction: number; elemental: number;
          fire: number; cold: number; lightning: number; erosion: number }
}

export interface NumbedInfo {
  base_per_stack: number      // 0.05 (or 0.11 if Conductive) — base Lightning Damage taken per stack
  conductive: boolean
  duration: number            // per-stack lifetime, seconds (2s × Ailment Duration)
  stacks: number              // effective stacks (max mode: user-set; real mode: computed steady state)
  max_stacks: number
  effect_inc: number          // Σ increased Numbed Effect
  effect_additional: number   // Σ additional Numbed Effect (multiplicative pool)
  lightning_taken: number     // final: base × (1+inc) × (1+additional) × stacks
  uptime_mode: 'max' | 'real'
  ff_duration?: number        // real mode: Feline Figure-inflicted Numbed duration (incl. Electroplated ×2)
  application_rate?: number   // real mode: Feline Figure trigger rate (≤1/s, single target)
}

export interface CoreTalentStatus {
  name: string
  text: string
  resolved: boolean
  kind: 'stat' | 'override' | 'deferred' | 'unresolved'
}

// ── Modifier resolution (inert-modifier badges) ─────────────────────────────────
export type ModifierSource = 'gear' | 'spirit' | 'memory' | 'talent' | 'slate' | 'skill'
export interface ModifierMapItem { key: string; text: string; source: ModifierSource; node_id?: string }
export interface ModifierMapResponse { results: Record<string, { stat_keys: string[] }> }

export const EMPTY_STAT_SHEET: StatSheetResponse = {
  stats: {},
  condition_maximums: {},
  clamp_report: {},
  offense: null,
  defense: null,
  consumed_stats: [],
  consumable_universe: [],
}

export type DiffStatus = 'added' | 'removed' | 'changed' | 'unchanged'

export interface DiffNode {
  index: number
  node_type: string
  status: DiffStatus
  stats_a: TalentStat[] | null
  stats_b: TalentStat[] | null
}

export interface DiffNamedTalent {
  name: string
  status: DiffStatus
  stats_a: TalentStat[] | null
  stats_b: TalentStat[] | null
}

export interface DiffTree {
  status: DiffStatus
  nodes: DiffNode[]
  core_talents: DiffNamedTalent[]
}

export interface TalentDiff {
  summary: {
    trees_added: number; trees_removed: number
    nodes_added: number; nodes_removed: number; nodes_changed: number
    core_talents_added: number; core_talents_removed: number; core_talents_changed: number
    new_god_added: number; new_god_removed: number; new_god_changed: number
  }
  trees: Record<string, DiffTree>
  new_god_talents: DiffNamedTalent[]
}

export interface SeasonSummary {
  name: string
  trees: string[]
  node_counts: Record<string, number>
  new_god_count: number | null
  legendary_gear_count: number | null
  skill_count: number | null
  hero_trait_count: number | null
  pact_spirit_count: number | null
  craft_base_type_count: number | null
  graft_count: number | null
  destiny_count: number | null
  ethereal_prism_count: number | null
  hero_memories_count: number | null
  memory_revival_count: number | null
  tower_sequence_count: number | null
  belt_blend_count: number | null
  is_active: boolean
}

export interface HeroTraitLevel {
  level: number
  effects: string[]
  unlock_level: number
}

export interface HeroAdvancedTrait {
  name: string
  unlock_level: number          // 45 | 60 | 75
  is_pick_one_from_two: boolean
  effects: string[]
  icon_url?: string | null      // render via iconUrl('hero_trait', icon_url) → bundled webp
}

export interface HeroTrait {
  trait_id: string
  hero: string
  variant_name: string
  description: string
  icon_url?: string | null      // render via iconUrl('hero_trait', icon_url) → bundled webp
  levels: HeroTraitLevel[]
  artificial_moon: { description: string; effects: string[] }
  advanced_traits: HeroAdvancedTrait[]
  max_level?: number | null
  glossary?: Record<string, { name: string; description: string }>
}

export interface PactSpiritSlot {
  name: string
  effect: string[]   // atomic stat lines (one stat per entry) — see pact_spirit_importer normalization
  ring: 'inner' | 'mid' | 'outer'
  icon_url?: string | null   // render via iconUrl('pactspirit', icon_url) → bundled webp
}

export interface PactSpiritRank {
  rank: number
  modifiers: string[]
}

export interface PactSpirit {
  item_id: string
  name: string
  description: string
  portrait_url?: string | null   // spirit's main icon; render via iconUrl('pactspirit', portrait_url)
  affinities: string[]
  main_skill_name: string
  main_skill_effect: string
  upgrade_ranks: PactSpiritRank[]
  slots: PactSpiritSlot[]
  glossary: Record<string, { name: string; description: string }>
}

export interface SelectedPactSpirit {
  itemId: string
  rank: number  // 1–6
}

// ── Pact Fates / Kismets (the /destiny `catalog`) ───────────────────────────────────────────────────
export type FateKind = 'micro_fate' | 'medium_fate' | 'kismet' | 'dual_kismet' | 'undetermined'
export interface FateCatalogItem {
  name: string
  short_name: string
  kind: FateKind
  node_tier: 'micro' | 'medium' | ''
  effect_text: string        // raw effect with (lo–hi) ranges (mid-substituted when emitted)
  icon_url?: string | null   // render via iconUrl('destiny', icon_url) once crawler icons land
}
export interface FateCatalog {
  items: FateCatalogItem[]
  micro: FateCatalogItem[]   // installable on micro (inner) nodes
  medium: FateCatalogItem[]  // installable on medium (mid) nodes (Medium Fates + Kismets + Dual Kismets)
  undetermined: FateCatalogItem | null
}
// A fate installed on a spirit node (or an undetermined extra slot).
export interface InstalledFate {
  name: string
  shortName: string
  kind: 'micro_fate' | 'medium_fate' | 'kismet' | 'dual_kismet'
  nodeTier: 'micro' | 'medium'
  effectText: string
  iconUrl?: string | null
}
// An Undetermined Fate installed below a spirit's outer node: grants extra micro/medium fate slots (right-to-left).
export interface UndeterminedFate {
  extraMicro: number   // 0–5
  extraMedium: number  // 0–3
  slots: (InstalledFate | null)[]   // length extraMicro+extraMedium; [0..extraMicro) micro, rest medium
}
export const FATE_MICRO_LIMIT = 9
export const FATE_MEDIUM_LIMIT = 4

// Substitute each "(lo–hi)" roll range with its midpoint (the default-roll convention).
export function fateMidEffect(effectText: string): string {
  return (effectText || '').replace(/\((\d+(?:\.\d+)?)\s*[–-]\s*(\d+(?:\.\d+)?)\)/g, (_m, a, b) => {
    const mid = (parseFloat(a) + parseFloat(b)) / 2
    return String(Number.isInteger(mid) ? mid : Math.round(mid * 100) / 100)
  })
}

// An effect line plus the display NAME of its origin (pact-spirit / hero-memory name). The backend echoes
// `source` onto each contribution's `source_name`, driving the stat-breakdown "Source Name" column.
export interface EffectInput { text: string; source: string }

export function buildSpiritEffects(
  selected: (SelectedPactSpirit | null)[],
  allSpirits: PactSpirit[],
  fates: Record<string, InstalledFate> = {},
  undetermined: (UndeterminedFate | null)[] = [],
): EffectInput[] {
  const effects: EffectInput[] = []

  // Dual Kismet pairing is build-wide: a dual kismet only grants its effect when 2 of the same are installed.
  const allInstalled: InstalledFate[] = [...Object.values(fates)]
  for (const u of undetermined) if (u) for (const f of u.slots) if (f) allInstalled.push(f)
  const dualCount: Record<string, number> = {}
  for (const f of allInstalled) if (f.kind === 'dual_kismet') dualCount[f.shortName] = (dualCount[f.shortName] || 0) + 1

  const emitFate = (f: InstalledFate) => {
    if (f.kind === 'dual_kismet' && (dualCount[f.shortName] || 0) < 2) return  // unpaired → no effect
    effects.push({ text: fateMidEffect(f.effectText), source: `Fate: ${f.shortName}` })
  }

  selected.forEach((sel, si) => {
    if (!sel) return
    const spirit = allSpirits.find(s => s.item_id === sel.itemId)
    if (!spirit) return
    const src = spirit.name
    // Inner/mid nodes: emit the installed fate's effect, else the node's own effect lines. Outer = rank modifiers.
    spirit.slots.forEach((slot, i) => {
      if (slot.ring === 'outer') return
      const f = fates[`${si}:${i}`]
      if (f) emitFate(f)
      else for (const t of slot.effect) effects.push({ text: t, source: src })
    })
    const rankData = spirit.upgrade_ranks.find(r => r.rank === sel.rank)
    if (rankData) for (const t of rankData.modifiers) effects.push({ text: t, source: src })

    // Undetermined Fate node: the combined +6% Damage / +6% Minion Damage generic, OR (when an Undetermined Fate
    // is installed) the extra slots it grants — each empty slot defaults to the generic for its tier.
    const u = undetermined[si]
    if (!u) {
      effects.push({ text: '+6 % Damage', source: 'Pact: Undetermined' })
      effects.push({ text: '+6 % Minion Damage', source: 'Pact: Undetermined' })
    } else {
      // Every empty extra slot grants the same generic +6% Damage / +6% Minion Damage regardless of micro/medium
      // (tier only governs size + what can be socketed, per owner).
      u.slots.forEach(f => {
        if (f) emitFate(f)
        else {
          effects.push({ text: '+6 % Damage', source: 'Pact: Undetermined' })
          effects.push({ text: '+6 % Minion Damage', source: 'Pact: Undetermined' })
        }
      })
    }
  })
  return effects
}

export interface DualStatGroup {
  value_index: number
  stat_keys: string[]
  unit?: string
}

export interface ResolvedAffixFields {
  stat_key?: string | null
  unit?: string
  stat_keys?: string[]
  is_range_split?: boolean
  min_stat_keys?: string[]
  max_stat_keys?: string[]
  dual_stat_groups?: DualStatGroup[]
}

export interface CraftAffix {
  raw_text: string
  expression: string
  condition: string | null
  affix_kind: 'numeric' | 'special' | 'placeholder'
  numeric_values: LegendaryNumericValue[]
  source: string
  affix_type: string
  tier: string
  stat_key?: string | null
  stat_keys?: string[]
  is_range_split?: boolean
  min_stat_keys?: string[]
  max_stat_keys?: string[]
  dual_stat_groups?: DualStatGroup[]
  unit?: string
}

export interface CraftBaseItem {
  name: string
  required_level: number
  armor: string | null
  implicits: string[]  // base item implicit stats (from crawler when available)
}

export interface CraftBaseType {
  item_id: string
  name: string
  affixes: CraftAffix[]
  base_items: CraftBaseItem[]
  corrosion_base_affixes?: Array<LegendaryAffix & { modifier_text: string }>
}

// Lightweight version — no affix pools, just base item metadata
export interface CraftBaseItemGroup {
  item_id: string
  name: string
  base_items: CraftBaseItem[]
}

export interface GraftAffix {
  raw_text: string
  expression: string
  condition: string | null
  affix_kind: 'numeric' | 'special' | 'placeholder'
  numeric_values: LegendaryNumericValue[]
  tier: string
  level: number
  weight: number
  affix_type: string
  // resolved by backend (/api/grafts) so vorax affixes carry stat keys like other gear
  stat_key?: string | null
  stat_keys?: string[]
  is_range_split?: boolean
  min_stat_keys?: string[]
  max_stat_keys?: string[]
  dual_stat_groups?: DualStatGroup[]
  unit?: string
}

export interface Graft {
  item_id: string
  name: string
  legendary_items: string[]
  base_affixes: GraftAffix[]
  affixes: GraftAffix[]
}

export interface DestinyItem {
  name: string
  text: string
}

export interface HeroMemoryAffix {
  tier: number
  modifier: string
  level: number
  weight: number
  source: string
}

export interface HeroMemoryType {
  name: string
  internal_id: number | null
  icon_url: string
}

export type MemoryRarity = 'normal' | 'magic' | 'rare' | 'epic' | 'ultimate'

export const MEMORY_RARITY_COLORS: Record<MemoryRarity, string> = {
  normal:   '#e0e0e0',
  magic:    '#4fc3f7',
  rare:     '#ce93d8',
  epic:     '#ffa726',
  ultimate: '#ef5350',
}

export interface MemorySlotSelection {
  modifier: string
  tier: number
  rolledValue: number | null
}

export interface CreatedHeroMemory {
  memoryType: 'origin' | 'discipline' | 'progress'
  rarity: MemoryRarity
  baseStat: MemorySlotSelection | null
  fixedAffixes: [MemorySlotSelection | null, MemorySlotSelection | null]
  randomAffixes: [MemorySlotSelection | null, MemorySlotSelection | null]
}

const MEMORY_NAMES: Record<CreatedHeroMemory['memoryType'], string> = {
  origin: 'Memory of Origin',
  discipline: 'Memory of Discipline',
  progress: 'Memory of Progress',
}

export function buildMemoryEffects(memories: (CreatedHeroMemory | null)[]): EffectInput[] {
  const effects: EffectInput[] = []
  const RANGE_RE = /\(\d+(?:\.\d+)?[–\-]\d+(?:\.\d+)?\)/g
  const resolveModifier = (sel: MemorySlotSelection): string => {
    // Ensure leading + for modifiers stored without it (handles legacy/missing-plus data)
    const mod = /^\d/.test(sel.modifier) ? '+' + sel.modifier : sel.modifier
    if (sel.rolledValue === null) return mod
    const val = Number.isInteger(sel.rolledValue) ? String(sel.rolledValue) : sel.rolledValue.toFixed(2)
    return mod.replace(RANGE_RE, val)
  }
  for (const mem of memories) {
    if (!mem) continue
    const src = MEMORY_NAMES[mem.memoryType] ?? 'Hero Memory'
    const push = (sel: MemorySlotSelection) => effects.push({ text: resolveModifier(sel), source: src })
    if (mem.baseStat) push(mem.baseStat)
    for (const fa of mem.fixedAffixes) { if (fa) push(fa) }
    for (const ra of mem.randomAffixes) { if (ra) push(ra) }
  }
  return effects
}

// Expand the level-scaling "( a / b / c / d / e )" notation in a hero-trait effect string to the value at
// `tierIndex` (0-based). Groups without a slash (plain parentheticals) are left untouched.
const _TRAIT_SLASH_RE = /\(([^()]*\/[^()]*)\)/g
function _expandTraitTier(text: string, tierIndex: number): string {
  return text.replace(_TRAIT_SLASH_RE, (_m, inner: string) => {
    const parts = inner.split('/').map(p => p.trim())
    return parts[Math.min(Math.max(tierIndex, 0), parts.length - 1)] ?? parts[parts.length - 1]
  })
}

// Build the engine `trait_effects` list from the selected hero trait. The base trait emits its chosen
// level's effect lines (+ Artificial Moon at max base level); each selected advanced trait emits its
// tier-expanded lines (tier = the slot level for that unlock tier: 45→slot1, 60→slot2, 75→slot3).
// For traits with a bespoke engine module these feed only the status surface; for generic traits the
// backend resolves them into contributions.
export function buildTraitEffects(
  traitId: string | null,
  traitSlotLevels: number[],
  advancedTraitSelections: string[],
  allTraits: HeroTrait[],
): EffectInput[] {
  if (!traitId) return []
  const trait = allTraits.find(t => t.trait_id === traitId)
  if (!trait) return []
  const out: EffectInput[] = []
  const src = trait.variant_name
  // A DISABLED node is a NEGATIVE slot level (the magnitude is its remembered level); skip disabled tiers.
  const slot = (i: number) => traitSlotLevels?.[i] ?? 1
  const tierEnabled = (i: number) => slot(i) >= 1
  const tierLevel = (i: number) => Math.max(1, Math.min(5, Math.abs(slot(i))))
  if (tierEnabled(0)) {
    const baseLevel = tierLevel(0)
    for (const e of trait.levels?.[baseLevel - 1]?.effects ?? []) out.push({ text: e, source: src })
    if (baseLevel >= 5) for (const e of trait.artificial_moon?.effects ?? []) out.push({ text: e, source: src })
  }
  const picks = new Set(advancedTraitSelections ?? [])
  for (const adv of trait.advanced_traits ?? []) {
    if (!picks.has(adv.name)) continue
    const slotIdx = adv.unlock_level >= 75 ? 3 : adv.unlock_level >= 60 ? 2 : 1
    if (!tierEnabled(slotIdx)) continue
    const tierIdx = tierLevel(slotIdx) - 1
    for (const e of adv.effects ?? []) out.push({ text: _expandTraitTier(e, tierIdx), source: adv.name })
  }
  return out
}

export interface MemoryRevivalAffix {
  tier: number
  modifier: string
  level: number
  weight: number
}

export interface TowerSequenceEntry {
  affix: string
  source: string
}

// One split effect line of a skill/support tooltip (from backend engine.tooltip.build_tooltip).
// `scaling` lines carry per-level resolved display strings in `values_by_level`; `special`/`flavor`
// lines are shown verbatim via `text`. `badge_text` is the canonical string fed to the badge resolver.
export interface SkillTooltipLine {
  kind: 'scaling' | 'special' | 'flavor'
  badge_text: string
  text: string
  values_by_level?: Record<number, string> | null
  // 'modeled' → engine models this skill's intrinsic mechanic (green badge), set backend-side for modeled
  // skills. null/absent → use the badge_text keys path (build-specific Consumed/Inactive/NYI).
  coverage?: 'modeled' | null
}

// Structured, level-aware tooltip for a skill/support. `level_kind` is "level" (skills/standard
// supports) or "tier" (noble/magnificent/activation). The renderer clamps the current level into
// `available_levels` (nearest ≤) and indexes each scaling line's `values_by_level`.
// Per-line roll metadata for a bespoke canvas support (engine.skill_effects.modeled_rolls). Drives the
// support panel's per-line roll slider, keyed by the same `identity` the engine reads (affix_identity of the
// tier line). `ranges_by_tier` holds the signed-fraction {min,max,mid} for each tier.
export interface SkillModeledRoll {
  identity: string
  stat_keys: string[]
  ranges_by_tier: Record<number, { min: number; max: number; mid: number }>
}

export interface SkillTooltipSpec {
  gate_text?: string | null   // support-target line ("Supports X Skills") — NOT rendered
  level_kind: 'level' | 'tier'
  default_level: number
  available_levels: number[]
  lines: SkillTooltipLine[]
  modeled_rolls?: SkillModeledRoll[]   // bespoke canvas-support roll lines (Howling Gale, Berserking Blade, …)
}

export interface SkillItem {
  item_id: string
  name: string
  internal_id?: number | null
  skill_type?: string
  is_aura?: boolean
  description_lines: string[]
  raw_text: string
  skill_tags: string[]
  max_level?: number | null
  mana_cost?: string | null
  cast_speed?: string | null
  weapon_restriction?: string | null
  main_stat?: string | null
  progression?: object[]
  tooltip?: SkillTooltipSpec
  // Whether this skill can contribute to the build's total DPS (dev-set; default derived from skill_type).
  dps_eligible?: boolean
  glossary?: Record<string, { name: string; description: string }>
}

export interface EquippedSupportSkill {
  support_index: number   // 1-5
  item_id: string
  name: string
  skill_type: string
  level: number
  // Rank (1-5) — Noble/Magnificent supports only. Scales the support's universal
  // "+% additional damage for the supported skill" line (R1 0% → R5 20%).
  rank?: number
  // Explicit per-line rolls (signed fraction) keyed by the line's affix identity. Overrides the
  // engine's tier-midpoint default for that line. See utils/supportRolls.ts + utils/affixIdentity.ts.
  specific_rolls?: Record<string, number>
  skill_tags: string[]
  description_lines: string[]
  // Whether this support contributes. Default true; false drops its contributions from the calc.
  // Persisted in the build (rides inside the skills array).
  enabled?: boolean
}

export interface EquippedSkill {
  slot: number            // 1-5 = active; 6-9 = passive
  item_id: string
  name: string
  level: number           // 20 = base; 21-30 = +10%/level; 31+ = +8%/level
  skill_tags: string[]
  description_lines: string[]
  supports: EquippedSupportSkill[]
  // Whether this skill (and its supports + sourced buffs/debuffs) contributes. Default true.
  enabled?: boolean
  // Whether this (dps_eligible) skill is included in the sidebar's total DPS. Default true; toggled per
  // skill on the Skills screen. Persisted in the build (rides in the skills array). Display-only — the
  // engine still computes every slot's offense regardless.
  countInDps?: boolean
}

const PASSIVE_TAGS = new Set(['Aura', 'Spirit Magus', 'Focus'])

export function isPassiveSkillItem(s: SkillItem): boolean {
  return s.skill_tags.some(t => PASSIVE_TAGS.has(t))
}

export function isActiveSkillItem(s: SkillItem): boolean {
  return !isPassiveSkillItem(s) &&
    !s.skill_tags.includes('Support') &&
    !s.description_lines[0]?.startsWith('Supports') &&
    !s.name.includes(':')
}

// Compound tag aliases: support text spelling → canonical skill tag
// ── Trait skill slot (Rosa High Court Chariot — Holy Domain) ──────────────────────
// A canonical slot index for the trait-granted skill's supports, kept clear of the 1-9 active/passive slots.
export const TRAIT_SKILL_SLOT = 10
export const TRAIT_SKILL_ID = 'rosa_holy_domain'
// The Holy Domain trait skill as a support-host (synthesized; deals no damage). Tags gate which supports attach.
export const TRAIT_SKILL_PARENT: EquippedSkill = {
  slot: TRAIT_SKILL_SLOT, item_id: TRAIT_SKILL_ID, name: 'Holy Domain',
  skill_type: 'active_skill', level: 1, skill_tags: ['Spell', 'Area', 'Channeled'],
  description_lines: [], supports: [],
} as unknown as EquippedSkill

/** Invulnerability or Divine Intervention (High Court Chariot) grants the Holy Domain support slot. */
export function traitGrantsSkillSlot(traitId: string | null, picks: string[]): boolean {
  return traitId === 'high_court_chariot'
    && (picks.includes('Invulnerability') || picks.includes('Divine Intervention'))
}

const TAG_ALIASES: Record<string, string> = {
  'Slash Strike': 'Slash-Strike',
}

function parseRequiredTags(phrase: string): string[] {
  let remaining = phrase
  const tags: string[] = []
  const sortedAliases = Object.keys(TAG_ALIASES).sort((a, b) => b.length - a.length)
  while (remaining.length > 0) {
    let matched = false
    for (const alias of sortedAliases) {
      if (remaining.toLowerCase().startsWith(alias.toLowerCase())) {
        tags.push(TAG_ALIASES[alias])
        remaining = remaining.slice(alias.length).trim()
        matched = true
        break
      }
    }
    if (!matched) {
      const m = remaining.match(/^(\S+)\s*(.*)$/)
      if (m) { tags.push(m[1]); remaining = m[2] }
      else break
    }
  }
  return tags
}

function checkTag(tag: string, skillTags: string[], isPassiveSlot: boolean): boolean {
  if (tag.toLowerCase() === 'active') return !isPassiveSlot
  if (tag.toLowerCase() === 'passive') return isPassiveSlot
  return skillTags.some(t => t.toLowerCase() === tag.toLowerCase())
}

// Whether a skill actually deals damage (vs a pure Aura / buff / Focus passive). Used to gate
// "Supports skills that deal damage" supports off non-damaging skills (e.g. an Aura like Electric Conversion).
function skillDealsDamage(skill: { skill_tags: string[] }): boolean {
  const dmgTags = ['attack', 'spell', 'minion', 'summon']
  return skill.skill_tags.some(t => dmgTags.includes(t.toLowerCase()))
}

export function isSupportCompatible(
  support: SkillItem,
  parentSkill: EquippedSkill,
  isPassiveSlot: boolean,
  supportIdx: number,
  isTraitSkillSlot = false   // the Holy Domain trait slot: a Support Skill OR Activation Medium support
): boolean {
  // Tag-based exclusion: certain support tags require the parent to share that tag
  if (support.skill_tags.includes('Spirit Magus') && !parentSkill.skill_tags.includes('Spirit Magus')) return false
  if (support.skill_tags.includes('Summon') && !parentSkill.skill_tags.includes('Summon')) return false
  if (support.skill_tags.includes('Spell') && !support.skill_tags.includes('Attack') &&
      !parentSkill.skill_tags.includes('Spell')) return false
  if (support.skill_tags.includes('Attack') && !support.skill_tags.includes('Spell') &&
      !parentSkill.skill_tags.includes('Attack')) return false

  // Activation Medium: any active skill, slot 1 only — EXCEPT the trait skill slot, which explicitly accepts
  // "a Support Skill or Activation Medium Support Skill" (Rosa Invulnerability / Divine Intervention).
  if (support.skill_tags.includes('Activation Medium')) {
    return isTraitSkillSlot || (!isPassiveSlot && supportIdx === 1)
  }

  // Skill-bound supports (Noble/Magnificent) carry a "<Parent Skill>: <Variant> (Tier)" name and lock to a
  // specific parent skill + slot. ONLY these genuinely-bound types use the colon branch — every skill-bound
  // colon support is noble/magnificent, while "Precise: X" (and other base support_skill colon names) are
  // quality-tier VARIANTS of normal supports. So Precise variants must be matched by their "Supports X"
  // description below (e.g. "Precise: Stand as One" → "Supports Aura Skills"), not hidden as a foreign binding.
  const skillBound = support.skill_type === 'noble_support_skill' || support.skill_type === 'magnificent_support_skill'
  if (skillBound && support.name.includes(':')) {
    const parentPart = support.name.split(':')[0].trim()
    if (parentSkill.name !== parentPart) return false
    const ordinals: [string, number][] = [
      ['first', 1], ['second', 2], ['third', 3], ['fourth', 4], ['fifth', 5],
    ]
    for (const descLine of support.description_lines) {
      if (descLine.includes('Support Skill Slot')) {
        for (const [word, num] of ordinals) {
          if (descLine.toLowerCase().includes(word)) return num === supportIdx
        }
      }
    }
    return true
  }

  // Generic "Supports X Skills" description parsing
  const firstLine = support.description_lines[0] || ''
  if (!firstLine.startsWith('Supports')) return false

  // The "Supports X Skills." requirement is ONLY the sentence up to its first period — the rest of the
  // line is the support's effect text (the importer concatenates the whole description into one line).
  // Without isolating it, the requirement parse choked on trailing effect text (e.g. Jump's "...or Chain
  // Skills. +2 Jumps..." never matched Chain), so most supports were wrongly hidden.
  const clauseMatch = firstLine.match(/^Supports\s+(.+?)\./)
  const raw = (clauseMatch ? clauseMatch[1] : firstLine.replace(/^Supports\s+/, '')).trim()
  if (raw.toLowerCase() === 'any skill' || raw.toLowerCase() === 'any skills') return true
  // "Supports skills that hit enemies / deal damage / summon …" all require an active damage/summon skill —
  // a pure Aura/buff/Focus passive matches none of them, so gate on the skill actually dealing damage. (This
  // is what stops Passivation, Added X Damage, Blind, etc. from showing for an Aura like Electric Conversion.)
  if (/^skills?\s+that/i.test(raw)) return skillDealsDamage(parentSkill)

  const alternatives = raw.split(/\s+or\s+/i)
  return alternatives.some(alt => {
    const andGroups = alt.split(/\s+and\s+/i)
    return andGroups.every(group => {
      const phrase = group.replace(/\s+skills?\s*$/i, '').trim()
      const required = parseRequiredTags(phrase)
      return required.every(tag => checkTag(tag, parentSkill.skill_tags, isPassiveSlot))
    })
  })
}

// Support slot energy costs (index 1-5 within each skill)
const SUPPORT_ACTIVE_COSTS  = [0, 10, 15, 50, 100]
const SUPPORT_PASSIVE_COSTS = [10, 10, 15, 50, 100]

export function getSupportEnergyCost(isPassive: boolean, supportIdx: number): number {
  const costs = isPassive ? SUPPORT_PASSIVE_COSTS : SUPPORT_ACTIVE_COSTS
  return costs[Math.max(0, Math.min(4, supportIdx - 1))]
}

// Per-gear-slot energy contribution (helm/gloves/boots/each 1H = 61; chest/2H = 122)
function gearSlotEnergy(slot: GearSlot | GearSlot[] | null): number {
  if (!slot) return 0
  if (Array.isArray(slot)) return slot.reduce((s, sl) => s + gearSlotEnergy(sl), 0)
  if (slot === 'chest') return 122
  if (slot === 'weapon1' || slot === 'weapon2') return 61  // refined when base_type known
  if (slot === 'helmet' || slot === 'gloves' || slot === 'boots') return 61
  return 0  // amulet, belt, ring1, ring2
}

export function getMaxEnergy(level: number, gear: EquippedGearItem[], effortlessCommand: boolean): number {
  const fromGear = gear.reduce((s, g) => s + gearSlotEnergy(g.slot), 0)
  return 4 + fromGear + Math.min(Math.max(level, 0), 100) + (effortlessCommand ? 1000 : 0)
}

// +1000 Max Energy comes from placing the Effortless Command Ethereal Prism (the engine grants it via the
// core-talent path; this derives the same for the client-side energy-budget display). Threshold-gated at 24 pts.
export function hasEffortlessCommandEnergy(prisms: PlacedPrism[], slots: (TreeSlot | null)[]): boolean {
  return (prisms ?? []).some(p => {
    if (p.kind !== 'ethereal_prism' || p.ethereal?.shortName !== 'Effortless Command') return false
    const ns = slots.find(s => s?.treeName === p.treeName)?.nodeStates ?? {}
    return Object.values(ns).reduce((a, b) => a + (b || 0), 0) >= 24
  })
}

export interface CharacterStatContribution {
  stat: string
  amount: number
  label: string
  text: string
}

// Baseline character stats every character has before gear/talents — Max Life, Max Mana, and
// Max Energy. The engine has no intrinsic base values (derive.py base = 0), so these are injected
// here as 'Base'/'Levels' character contributions.
//   Max Life:   50 base + 13 per level
//   Max Mana:   40 base +  5 per level
//   Max Energy:  4 base +  1 per level (+ gear slots, + Prism)
// NOTE (revisit): base regen is NOT modeled — Life regen over time; Mana 7/s + 1.75%/s. Needs
// regen stats in the engine. Likewise Temporary Life/Mana and Base-Max variants are unmodeled.
export function buildCharacterContributions(
  gear: EquippedGearItem[],
  characterLevel: number,
): CharacterStatContribution[] {
  const contribs: CharacterStatContribution[] = []
  const lvl = Math.min(Math.max(characterLevel, 0), 100)
  // Per-level scaling is per level GAINED — a player starts at level 1 with the base value, so
  // multiply by (level - 1), not level.
  const levelsGained = Math.max(lvl - 1, 0)

  const baseLife = 50 + 13 * levelsGained
  contribs.push({ stat: 'max_life_flat', amount: baseLife, label: 'Base', text: `+${baseLife} Max Life (50 + 13/level)` })

  const baseMana = 40 + 5 * levelsGained
  contribs.push({ stat: 'max_mana_flat', amount: baseMana, label: 'Base', text: `+${baseMana} Max Mana (40 + 5/level)` })

  // Base Evasion = 2 per level gained (Help DB: "Players have 0 Evasion by default. Evasion increased by 2 for
  // every level gained."). Scaled by % increased Evasion via the engine's evasion_flat pool.
  const baseEvasion = 2 * levelsGained
  if (baseEvasion > 0) contribs.push({ stat: 'evasion_flat', amount: baseEvasion, label: 'Base', text: `+${baseEvasion} Evasion (2/level)` })

  contribs.push({ stat: 'max_energy_flat', amount: 4, label: 'Base', text: '+4 Max Energy' })
  const gearE = gear.reduce((s, g) => s + gearSlotEnergy(g.slot), 0)
  if (gearE > 0) contribs.push({ stat: 'max_energy_flat', amount: gearE, label: 'Gear', text: `+${gearE} Max Energy` })
  if (lvl > 0) contribs.push({ stat: 'max_energy_flat', amount: lvl, label: 'Levels', text: `+${lvl} Max Energy` })
  // +1000 Max Energy (Effortless Command) is granted by the engine when that Ethereal Prism is placed — no
  // longer a manual toggle here (it would double-count with the prism's core-talent grant).
  return contribs
}

export interface LegendaryNumericValue {
  kind: 'range' | 'fixed'
  sign: string | null
  // range
  min?: number
  max?: number
  // fixed
  value?: number
  raw: string
}

export interface LegendaryAffix {
  raw_text: string
  modifier_id: string | null
  expression: string
  condition: string | null
  affix_kind: 'numeric' | 'special' | 'tagged' | 'placeholder' | 'implicit'
  numeric_values: LegendaryNumericValue[]
  // resolved by backend at load time
  stat_key?: string | null
  stat_keys?: string[]
  is_range_split?: boolean
  min_stat_keys?: string[]
  max_stat_keys?: string[]
  dual_stat_groups?: DualStatGroup[]
  unit?: string
  // set for crafted/vorax items: 'Base' | 'Basic Affix' | 'Advanced Affix' | 'Ultimate Affix' | 'Legendary'
  affix_type?: string
  // roll tier (T1/T2/…) on crafted/graft affixes; shown prefixed on the affix-kind label in tooltips
  tier?: string | number

  // resolved by backend: structured engine expression if condition text was mapped
  condition_expr?: Record<string, unknown> | string | null
}

export interface LegendaryGearVariant {
  implicits: LegendaryAffix[]
  explicits: LegendaryAffix[]
}

export interface LegendaryRandomAffixGroup {
  placeholder: string
  options: LegendaryAffix[]
}

export interface LegendaryGearIndexItem {
  item_id: string
  name: string
  required_level: number
  base_type: string
}

export interface LegendaryGearItem {
  item_id: string
  name: string
  internal_id: number | null
  base_type: string
  required_level: number
  drop_level: number | null
  flavor_text: string | null
  drop_sources: string[]
  glossary: Record<string, { name: string; description: string }>
  variants: Record<string, LegendaryGearVariant>
  random_affixes: Record<string, LegendaryRandomAffixGroup[]>
}

export type GearSlot = 'helmet' | 'amulet' | 'chest' | 'gloves' | 'belt'
                     | 'boots' | 'ring1' | 'ring2' | 'weapon1' | 'weapon2'

export interface CustomizedAffix {
  affix_index: number
  chosen_values: Record<number, number>   // value_index → chosen number
  chosen_placeholder_key: string | null
}

export interface EquippedGearItem {
  item_id: string
  name: string
  required_level: number
  affixes: LegendaryAffix[]
  customizations: CustomizedAffix[]
  slot: GearSlot | GearSlot[] | null
  base_type?: string
  is_crafted?: boolean
  is_vorax?: boolean
  legendary_source?: string | null
  legendary_affix_count?: number
  base_stats?: Record<string, number>
  implicit_count?: number
  craft_slot_positions?: number[]
  corrosion_type?: 'none' | 'desecration' | 'mutation'
  corroded_explicit_indices?: number[]
  mutation_affix_text?: string | null
  mutation_resolved_affix?: LegendaryAffix | null
  selected_random_affixes?: Record<number, string>
  // Equipped belt blend (Blending Ritual) — the blend's talent_id. Belt slot only; one blend total.
  // Grants the blend's exclusive Core/Aromatic/Medium effect (resolved by the engine, roadmap #4).
  beltBlend?: string | null
}

// One entry from the Belt Blends (Blending Rituals) catalog — see backend belt_blend_importer.
export interface BeltBlend {
  talent_id: string
  talent_type: 'core' | 'aromatic' | 'medium' | string
  talent_level: number
  talent_name: string | null
  effect_text: string
  effect_raw: string
}

export interface GearAffixContribution {
  stat: string
  display_value: number
  unit: string
  item_name: string
  text?: string  // affix raw_text — per-affix "additional" pooling identity (Option A)
  slot: string | null
  condition?: Record<string, unknown> | string | null
}

// ── Damage-delta contract (tooltip damage-preview band) ──────────────────────────
// Describes a hypothetical build change to price against the current build. The backend
// endpoint that consumes this is NOT BUILT YET — see docs/TOOLTIP_REVAMP_HANDOFF.md §6.
export type HypotheticalChange =
  // allocate_node prices the marginal next point (or, when maxed, removing the last point).
  // The hook reads the node's current points from the build and steps by ±1; max_points tells
  // it whether the next step is an add or a removal.
  | { kind: 'allocate_node'; node_id: string; max_points: number }
  | { kind: 'equip_gear'; slot: GearSlot; item_id: string }
  | { kind: 'place_slate'; slate_id: string }
  | { kind: 'socket_memory'; slot: number; memory_id: string }
  | { kind: 'pact_spirit_node'; node_id: string }

export interface DamageDeltaResult {
  supported: boolean   // false → render the NYI band (engine's all-or-nothing per-skill support)
  absolute: number     // change in the headline damage metric
  percent: number      // change as a percentage of current
}

export interface GearEngineItem {
  contributions: GearAffixContribution[]
  // Core-talent grants riding with this gear item (roadmap #4), read server-side by resolve_core_talents:
  //  - belt_blend: the belt's equipped blend talent_id (belt item only).
  //  - granted_talents: bracket-named core talents this item grants ("[Name] …" legendary affixes).
  belt_blend?: string | null
  granted_talents?: string[]
  // Raw affix/implicit texts the frontend couldn't resolve (e.g. crafted base resistances/life).
  // The backend resolves and applies these, and reports any it still can't — so nothing is dropped.
  unresolved_texts?: string[]
  // Item-level name for attributing unresolved_texts (e.g. a dual-wield weapon's name). Per-contribution
  // item_name covers typed contributions; this covers the unresolved-text channel.
  item_name?: string
}

export interface SeasonDiffNode {
  id: string
  node_type: string
  max_points: number
  effects: string[]
}

export interface SeasonDiffNodeChange {
  id: string
  old: SeasonDiffNode | null
  new: SeasonDiffNode | null
}

export interface SeasonDiffTree {
  status: 'added' | 'removed' | 'changed' | 'unchanged'
  nodes_added: SeasonDiffNode[]
  nodes_removed: SeasonDiffNode[]
  nodes_changed: SeasonDiffNodeChange[]
  connections_added: { from: string; to: string }[]
  connections_removed: { from: string; to: string }[]
}

export interface ImportCrawlerTreeResult {
  ok: boolean
  tree_name: string
  node_count?: number
  core_talent_count?: number
  connection_count?: number
  count?: number
}

export interface SeasonDiff {
  summary: {
    trees_added: number
    trees_removed: number
    nodes_added: number
    nodes_removed: number
    nodes_changed: number
    connections_added: number
    connections_removed: number
  }
  trees: Record<string, SeasonDiffTree>
}

export const api = {
  getTrees: () => get<{ name: string; color: string }[]>('/trees'),

  // Cross-tree node search for the overview — trees with nodes matching the query + per-tree match count.
  searchTrees: (q: string) => get<{ name: string; match_count: number }[]>(`/tree-search?q=${encodeURIComponent(q)}`),

  getTree: (name: string) => get<TreeData>(`/tree/${encodeURIComponent(name)}`),

  getBuilds: () => get<Build[]>('/builds'),
  postBuild: (build: { id?: string; name: string; slots: (TreeSlot | null)[]; slates?: SavedSlate[]; conditionState?: Record<string, number | boolean> }) =>
    post<Build>('/builds', build),
  deleteBuild: (id: string) => del<{ ok: boolean }>(`/builds/${id}`),

  encodeBuildCode: (build: object) =>
    post<{ code: string }>('/build-code/encode', { build }),
  decodeBuildCode: (code: string) =>
    post<{ build: Record<string, unknown> }>('/build-code/decode', { code }),

  // Share service — store/fetch a build code by short id (public host).
  shareBuildCode: (code: string) =>
    postToShareService<{ id: string; url: string }>('/b', { code }),
  fetchSharedBuildCode: (id: string) =>
    getFromShareService(`/b/${id}`),

  // Tree editing (debug tools)
  upsertNode: (tree: string, node: NodeEditData) =>
    post<{ ok: boolean }>(`/tree/${encodeURIComponent(tree)}/node`, node),
  removeNode: (tree: string, nodeId: string) =>
    del<{ ok: boolean }>(`/tree/${encodeURIComponent(tree)}/node/${encodeURIComponent(nodeId)}`),
  toggleConnection: (tree: string, src: string, dst: string) =>
    post<{ ok: boolean }>(`/tree/${encodeURIComponent(tree)}/connection`, { src, dst }),

  getModifierPool: () => get<ModPoolEntry[]>('/modifier-pool'),

  // Dev tools
  parseTalentDoc: async (file: File): Promise<TalentSnapshot> => {
    if (ipcMode) {
      rlog('parseTalentDoc (IPC) — reading file bytes')
      const bytes = new Uint8Array(await file.arrayBuffer())
      const result = await window.api!.apiFormUpload('/dev/parse-talent-doc', bytes, file.name) as { ok: boolean; status: number; data: TalentSnapshot }
      if (!result.ok) return Promise.reject(result.data ?? 'Upload failed')
      return result.data
    }
    const form = new FormData()
    form.append('file', file)
    const r = await fetch(`${BASE}/dev/parse-talent-doc`, { method: 'POST', body: form })
    if (!r.ok) return Promise.reject((await r.json()).detail ?? r.statusText)
    return r.json()
  },
  diffSnapshots: (a: TalentSnapshot, b: TalentSnapshot): Promise<TalentDiff> =>
    post<TalentDiff>('/dev/diff-snapshots', { snapshot_a: a, snapshot_b: b }),

  saveCanonicalSnapshot: (snapshot: TalentSnapshot): Promise<{ ok: boolean; source_file: string; generated_at: string }> =>
    post<{ ok: boolean; source_file: string; generated_at: string }>('/dev/save-snapshot', { snapshot }),
  getSnapshotStatus: () => get<SnapshotStatus>('/dev/snapshot-status'),
  rebuildNodeTypeFilter: () => post<RebuildFilterResult>('/dev/rebuild-node-type-filter', {}),
  exportStatMeta: () => post<{ ok: boolean; stat_count: number; path: string }>('/dev/export-stat-meta', {}),
  exportUnmatched: () => post<{ ok: boolean; total: number; unique: number; path: string }>('/dev/export-unmatched', {}),
  getNodeTypeFilterOverrides: () => get<{ overrides: Record<string, FilterOverride> }>('/dev/node-type-filter/overrides'),
  addNodeTypeFilterOverride: (text: string, stat: string) => post<{ ok: boolean; key: string }>('/dev/node-type-filter/overrides', { text, stat }),
  deleteNodeTypeFilterOverride: (key: string) => del<{ ok: boolean }>(`/dev/node-type-filter/overrides/${encodeURIComponent(key)}`),
  getStatRecipes: (treeName: string, nodeType: string) =>
    get<StatRecipe[]>(`/dev/stat-recipes/${encodeURIComponent(treeName)}/${encodeURIComponent(nodeType)}`),
  getSnapshotModifiers: (treeName: string, nodeType: string) =>
    get<SnapshotModifier[]>(`/dev/snapshot-modifiers/${encodeURIComponent(treeName)}/${encodeURIComponent(nodeType)}`),

  clearSnapshot: () => del<{ ok: boolean }>('/dev/snapshot'),
  clearNodeTypeFilter: () => del<{ ok: boolean }>('/dev/node-type-filter'),

  // Seasons
  listSeasons: () => get<SeasonSummary[]>('/seasons'),
  getActiveSeason: () => get<{ name: string | null }>('/active-season'),
  setActiveSeason: (name: string | null) => post<{ ok: boolean }>('/active-season', { name }),
  deleteSeason: (name: string) => del<{ ok: boolean }>(`/seasons/${encodeURIComponent(name)}`),
  importSeason: (seasonName: string, nodes: object[]) =>
    post<{ ok: boolean; trees_imported: string[]; skipped: string[] }>(
      '/dev/import-season', { season_name: seasonName, nodes }
    ),
  importNewGodTalents: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; count: number }>(
      '/dev/import-new-god-talents', { season_name: seasonName, items }
    ),
  importLegendaryGear: (seasonName: string, fileData: object) =>
    post<{ ok: boolean; count: number; set_name: string }>(
      '/dev/import-legendary-gear', { season_name: seasonName, file_data: fileData }
    ),
  importCrawlerLegendaryGear: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; count: number }>(
      '/dev/import-crawler-legendary-gear',
      { season_name: seasonName, items }
    ),
  importSkills: (seasonName: string, fileData: object) =>
    post<{ ok: boolean; added: number; total: number }>(
      '/dev/import-skills', { season_name: seasonName, file_data: fileData }
    ),
  importCrawlerSkills: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; added: number; total: number }>(
      '/dev/import-crawler-skills', { season_name: seasonName, items }
    ),
  getSkills: () => get<{ season: string | null; skills: SkillItem[] }>('/skills'),
  getLegendaryGearIndex: () => get<{ season: string | null; items: LegendaryGearIndexItem[] }>('/legendary-gear-index'),
  getLegendaryGear: () => get<{ season: string | null; items: LegendaryGearItem[] }>('/legendary-gear'),
  clearSkills: () => del<{ ok: boolean }>('/dev/skills'),

  importCrawlerTree: (seasonName: string, treeName: string, crawlerData: object) =>
    post<ImportCrawlerTreeResult>(
      '/dev/import-crawler-tree',
      { season_name: seasonName, tree_name: treeName, crawler_data: crawlerData }
    ),

  importHeroTrait: (seasonName: string, fileData: object) =>
    post<{ ok: boolean; hero: string; total: number; heroes: number }>(
      '/dev/import-hero-traits', { season_name: seasonName, file_data: fileData }
    ),
  importCrawlerHeroTraits: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; added: number; total: number; heroes: number }>(
      '/dev/import-crawler-hero-traits', { season_name: seasonName, items }
    ),
  getHeroTraits: () => get<{ season: string | null; traits: HeroTrait[] }>('/hero-traits'),
  clearHeroTraits: () => del<{ ok: boolean }>('/dev/hero-traits'),

  importCrawlerPactSpirits: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; count: number }>(
      '/dev/import-crawler-pact-spirits', { season_name: seasonName, items }
    ),
  getPactSpirits: () => get<{ season: string | null; spirits: PactSpirit[] }>('/pact-spirits'),
  clearPactSpirits: () => del<{ ok: boolean }>('/dev/pact-spirits'),

  importCrawlerCraftBaseTypes: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; count: number }>(
      '/dev/import-crawler-craft-base-types', { season_name: seasonName, items }
    ),
  getCraftBaseTypes: () => get<{ season: string | null; base_types: CraftBaseType[] }>('/craft-base-types'),
  resolveGearAffixes: (texts: string[]) =>
    post<{ results: Record<string, ResolvedAffixFields> }>('/resolve-gear-affixes', { texts }),
  getCraftBaseItems: () => get<{ season: string | null; base_types: CraftBaseItemGroup[] }>('/craft-base-items'),
  clearCraftBaseTypes: () => del<{ ok: boolean }>('/dev/craft-base-types'),

  importCrawlerGrafts: (seasonName: string, items: object[]) =>
    post<{ ok: boolean; count: number }>(
      '/dev/import-crawler-grafts', { season_name: seasonName, items }
    ),
  getGrafts: () => get<{ season: string | null; grafts: Graft[] }>('/grafts'),
  clearGrafts: () => del<{ ok: boolean }>('/dev/grafts'),

  // Belt Blends (Blending Rituals) — a single scraper file: { entries, glossary }.
  importCrawlerBeltBlends: (seasonName: string, data: object) =>
    post<{ ok: boolean; count: number }>(
      '/dev/import-crawler-belt-blends', { season_name: seasonName, data }
    ),
  getBeltBlends: () => get<{ season: string | null; blends: BeltBlend[]; glossary: Record<string, { name: string; description: string }> }>('/belt-blends'),
  clearBeltBlends: () => del<{ ok: boolean }>('/dev/belt-blends'),

  importDestiny: (seasonName: string, data: object) =>
    post<{ ok: boolean; count: number }>('/dev/import-destiny', { season_name: seasonName, data }),
  getDestiny: () => get<{ season: string | null; items: DestinyItem[]; catalog?: FateCatalog }>('/destiny'),

  importEtherealPrism: (seasonName: string, data: object) =>
    post<{ ok: boolean; count: number }>('/dev/import-ethereal-prism', { season_name: seasonName, data }),
  getEtherealPrism: () => get<PrismCatalog>('/ethereal-prism'),

  importHeroMemories: (seasonName: string, data: object) =>
    post<{ ok: boolean; count: number }>('/dev/import-hero-memories', { season_name: seasonName, data }),
  getHeroMemories: () => get<{
    season: string | null
    memory_types: HeroMemoryType[]
    fixed_affixes: HeroMemoryAffix[]
    random_affixes: HeroMemoryAffix[]
    base_stats: HeroMemoryAffix[]
  }>('/hero-memories'),

  importMemoryRevival: (seasonName: string, data: object) =>
    post<{ ok: boolean; count: number }>('/dev/import-memory-revival', { season_name: seasonName, data }),
  getMemoryRevival: () => get<{ season: string | null; affixes: MemoryRevivalAffix[] }>('/memory-revival'),

  importTowerSequence: (seasonName: string, data: object) =>
    post<{ ok: boolean; count: number }>('/dev/import-tower-sequence', { season_name: seasonName, data }),
  getTowerSequence: () => get<{ season: string | null; entries: TowerSequenceEntry[] }>('/tower-sequence'),

  diffSeasons: (seasonA: string, seasonB: string) =>
    post<SeasonDiff>('/dev/diff-seasons', { season_a: seasonA, season_b: seasonB }),

  getSlatePool: (primaryTree: string) =>
    get<SlatePool>(`/slate-pool/${encodeURIComponent(primaryTree)}`),
  getSlatePoolAll: () => get<SlatePool>('/slate-pool-all'),

  engineCompute: (payload: {
    slots: ({ treeName: string; nodeStates: Record<string, number> } | null)[]
    slates?: SavedSlate[]
    conditions?: string[]
    skill: {
      name: string; skill_type: string; tags: string[]; damage_types: string[]
      base_level: number; extra_levels?: number
      base_dmg_min?: number; base_dmg_max?: number; base_csr?: number
    }
    enemy?: {
      fire_resistance?: number; cold_resistance?: number
      lightning_resistance?: number; erosion_resistance?: number; armor?: number
    }
  }) => post<{
    avg_hit: number; min_hit: number; max_hit: number
    crit_chance: number; crit_multiplier: number; effective_dps: number
    breakdown: Record<string, unknown>
  }>('/engine/compute', payload),

  engineStats: (payload: {
    slots: ({ treeName: string; nodeStates: Record<string, number> } | null)[]
    slates?: SavedSlate[]
    condition_state?: Record<string, number | boolean>
    gear?: GearEngineItem[]
    character?: CharacterStatContribution[]
    memory_effects?: EffectInput[]
    spirit_effects?: EffectInput[]
    main_skill?: SkillEngineInput | null
    skills?: SkillSlotInput[]
    custom_mods?: string[]
    attached_supports?: AttachedSupportInput[]
  }): Promise<StatSheetResponse> => post<StatSheetResponse>('/engine/stats', payload),

  resolveMod: (text: string) =>
    post<ResolveModResponse>('/resolve-mod', { text }),

  // Map raw modifier texts (spirit/memory/talent/slate) to engine stat key(s). Deterministic per
  // data version; the renderer caches results in mappingStore. Gear carries stat_key already.
  mapModifiers: (items: ModifierMapItem[]) =>
    post<ModifierMapResponse>('/map-modifiers', { items }),

  getConditions: () => get<Record<string, ConditionDef[]>>('/conditions'),

  // ── Dev: condition manager ─────────────────────────────────────────────────
  devGetStatKeys: () =>
    get<{ keys: string[] }>('/dev/conditions/stat-keys'),
  devGetConditionDefs: () =>
    get<ConditionDefsResponse>('/dev/conditions/definitions'),
  devSaveConditionDef: (def: ConditionDef) =>
    post<{ ok: boolean }>('/dev/conditions/definitions', def),
  devUpdateConditionDef: (key: string, def: ConditionDef) =>
    put<{ ok: boolean }>(`/dev/conditions/definitions/${key}`, def),
  devDeleteConditionDef: (key: string) =>
    del<{ ok: boolean }>(`/dev/conditions/definitions/${key}`),
  devUpsertDerivedKey: (boolKey: string, stackKey: string) =>
    post<{ ok: boolean }>('/dev/conditions/derived-keys', { bool_key: boolKey, stack_key: stackKey }),
  devDeleteDerivedKey: (boolKey: string) =>
    del<{ ok: boolean }>(`/dev/conditions/derived-keys/${boolKey}`),
  devGetConditionSources: () =>
    get<{ season: string | null; entries: ConditionSourceEntry[] }>('/dev/conditions/sources'),
  devGetConditionSourceItems: (text: string) =>
    get<{ items: { source: string; item_name: string; affix_text: string }[] }>(`/dev/conditions/source-items?text=${encodeURIComponent(text)}`),
  devGetConditionOverrides: () =>
    get<Record<string, unknown>>('/dev/conditions/overrides'),
  devSaveConditionOverride: (conditionText: string, expression: unknown) =>
    post<{ ok: boolean }>('/dev/conditions/overrides', { condition_text: conditionText, expression }),
  devDeleteConditionOverride: (conditionText: string) =>
    del<{ ok: boolean }>('/dev/conditions/overrides', { condition_text: conditionText, expression: null }),

  validateAllocate: (
    tree_name: string,
    node_states: Record<string, number>,
    node_id: string,
    action: 'allocate' | 'deallocate',
    prereq_satisfied: string[] = [],
    max_overrides: Record<string, number> = {},
    extra_column_points: Record<number, number> = {}
  ) => post<{ allowed: boolean; reason?: string; node_states: Record<string, number> }>('/validate-allocate', {
    tree_name, node_states, node_id, action, prereq_satisfied, max_overrides, extra_column_points,
  }),
}
