import { describe, it, expect } from 'vitest'
import zlib from 'node:zlib'
import { decodeBuildCodeLean, LeanBuildCodeError } from '../utils/decodeBuildCodeLean'

// Hand-rolled encoder for malformed-input tests only (real fixtures above come from the actual
// Python encoder) — matches the same base64url(zlib(json)) pipeline so it can construct payloads
// Python's own encoder would never produce (e.g. a non-numeric `v`), to prove the decoder rejects
// them rather than silently trusting an out-of-contract value.
function encodeForTest(obj: unknown): string {
  const compressed = zlib.deflateSync(Buffer.from(JSON.stringify(obj), 'utf-8'), { level: 9 })
  const b64url = compressed.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
  return `tli1_${b64url}`
}

// Generated by the REAL Python encoder (zlib.compress + base64.urlsafe_b64encode, matching
// backend/build_code.py's encode_build pipeline exactly) — not produced by any TS code here. This
// is the critical cross-runtime claim this file exists to prove: the browser's
// DecompressionStream('deflate') can inflate what Python's zlib.compress() produces, since the
// decoder can never be tested against itself and call that "compatibility."
const REAL_PYTHON_CODE =
  'tli1_eNpdkNFqwzAMRX8l6DmMdm_N8ygMxn5gFKPZSiri2EFW0ozSf5_jdKPbm5B0dO_VFewZBa2SvNFMHprDroaOUKD5uAIrDYYdNLkajKeOgkP5MnuoIfmoeXAhHGPYw62-ArYtL5QKWmrTc1jpMA0kbDNlY3CsHAM0YfK-BlpGoZRKB5SSVoXMq0N03DJJMbAt3--YGf1UdE41CF6M0qJ_8VuecDJWsFXKvMpE9b889-FjGnvOJwoccKDceCEbHUl15EUnoXWzZ--3jI6SFR7XOMZzKI4ygT5VDgfs6AlOj6Kp90XMb69-3v3KHCUmbVmoeo8z_qgYxe6ecvO3z8U0jlG0tFefKsj6ul7_JEkkPUnG53z99g1-M6N4'

const EXPECTED = {
  v: 2,
  name: 'Decoder Fixture',
  characterLevel: 90,
  traitId: 'berserker',
  gear: [
    { item_id: 'itm_legendary_1', slot: 'weapon1' },
    {
      item_id: 'itm_crafted_1',
      slot: 'chest',
      is_crafted: true,
      affixes: [{
        raw_text: 'test affix', modifier_id: null, expression: 'test affix',
        condition: null, affix_kind: 'numeric', numeric_values: [],
      }],
    },
  ],
  skills: [{
    slot: 1, item_id: 'skl_1', name: 'Frostfire Nova', level: 20,
    skill_tags: [], description_lines: ['Deals damage.'], supports: [],
  }],
}

describe('decodeBuildCodeLean', () => {
  it('decodes a real Python-encoded tli1 code byte-for-byte into the original JSON', async () => {
    const decoded = await decodeBuildCodeLean(REAL_PYTHON_CODE)
    expect(decoded).toEqual(EXPECTED)
  })

  it('splits on the FIRST underscore only — a payload containing "_" is not mis-parsed', async () => {
    // Sanity check on the fixture itself: prove it actually contains a base64url '_' character,
    // so the "split on first underscore only" logic is genuinely exercised above, not vacuously
    // true because the fixture happened to have none.
    const payload = REAL_PYTHON_CODE.slice('tli1_'.length)
    expect(payload.includes('_')).toBe(true)
  })

  it('rejects a bad prefix', async () => {
    await expect(decodeBuildCodeLean('tli2_abc')).rejects.toThrow(LeanBuildCodeError)
  })

  it('rejects invalid base64', async () => {
    await expect(decodeBuildCodeLean('tli1_!!!not-base64!!!')).rejects.toThrow(LeanBuildCodeError)
  })

  it('rejects corrupt (non-inflatable) payload', async () => {
    await expect(decodeBuildCodeLean('tli1_AAAA')).rejects.toThrow(LeanBuildCodeError)
  })

  it('rejects an empty string', async () => {
    await expect(decodeBuildCodeLean('')).rejects.toThrow(LeanBuildCodeError)
  })

  it('rejects a non-numeric schema version instead of silently trusting it', async () => {
    const code = encodeForTest({ v: 'not-a-number', gear: [], skills: [] })
    await expect(decodeBuildCodeLean(code)).rejects.toThrow(LeanBuildCodeError)
  })

  it('rejects a schema version newer than this decoder has ever been checked against', async () => {
    const code = encodeForTest({ v: 999, gear: [], skills: [] })
    await expect(decodeBuildCodeLean(code)).rejects.toThrow(LeanBuildCodeError)
  })

  it('accepts a build with no `v` field at all (pre-versioning codes)', async () => {
    const decoded = await decodeBuildCodeLean(encodeForTest({ gear: [], skills: [] }))
    expect(decoded).toEqual({ gear: [], skills: [] })
  })
})
